### ISSUE TITLE
How to perform scVelo analysis on Seurat subtypes

### ISSUE THREAD

**Issue by asdfasf4safasg** [Starlitnightly/omicverse#101]
When I was performing scVelo analysis, I first divided the single-cell data into main clusters, then extracted a group from the main clusters and further subdivided it into subtypes. However, when I directly used the UMAP analysis on the subset subtypes, I found that the analysis results were different from the pattern of the subset. Therefore, I had to map the subtypes back to the main clusters for analysis. I would like to ask how I can directly analyze the results of the subset.
cur_celltypes = ['Astrocytes','Interneurons']
"adata_subset = adata[adata.obs['celltype'].isin(cur_celltypes)]"

**Comment by Starlitnightly** [comment]
Sry, i didn't understand what's mean of ` I found that the analysis results were different from the pattern of the subset.` 

Perhaps you could use a diagram to represent your question in analyse.

Regards,
Zehua

**Comment by asdfasf4safasg** [comment]
<img width="335" alt="image" src="https://github.com/Starlitnightly/omicverse/assets/134588018/8b298cee-09ae-4400-87d1-033b107bc48c">
<img width="346" alt="image" src="https://github.com/Starlitnightly/omicverse/assets/134588018/8a366074-825e-41d7-a0ab-abeb7cafa0e7">
<img width="275" alt="image" src="https://github.com/Starlitnightly/omicverse/assets/134588018/67ac14cc-356d-4a77-a569-cb33041dccdb">
After subsetting the colored figure from the main figure and reanalyzing it, how can I, in subsequent scVelo analyses, focus only on the subtype part but ensure the analysis is based on the subtype itself and not just on the main figure’s pattern?

**Comment by Starlitnightly** [comment]
![image](https://github.com/Starlitnightly/omicverse/assets/46667721/6512193e-ad15-47ab-8085-d54f65bb4f4d)

All the analyses you are doing on this diagram are subtype related, not related to all the cells, you can re-run the clustering algorithms like leiden on subtype if you are not satisfied with raw clusters.

Zehua

**Comment by asdfasf4safasg** [comment]
不好意思，刚才微信只是想要留言，没有要你及时回复的意思。我能不能用中文回复，我可能英文没有描述清楚，就是scvelo的分析我想要的pattern是从main celltype中提取的subtype的pattern，而不是main celltype在scvelo分析的时候提取子集分析然后用的main celltype的pattern

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Zehua Zeng ***@***.***>
发送时间: Friday, July 5, 2024 11:14:08 PM
收件人: Starlitnightly/omicverse ***@***.***>
抄送: Lili ZHOU 周丽丽 ***@***.***>; Author ***@***.***>
主题: Re: [Starlitnightly/omicverse] How to perform scVelo analysis on Seurat subtypes (Issue #101)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

image.png (view on web)<https://github.com/Starlitnightly/omicverse/assets/46667721/6512193e-ad15-47ab-8085-d54f65bb4f4d>

All the analyses you are doing on this diagram are subtype related, not related to all the cells, you can re-run the clustering algorithms like leiden on subtype if you are not satisfied with raw clusters.

Zehua

―

**Comment by Starlitnightly** [comment]
没太看懂你的问题，你要计算subtype在subtype上单独运行你的分析就好，例如在subtype上运行velocity。如果英文都表述不清楚那中文更难表述清楚。例如，如果你是想保留main celltype的umap结果，那你就不要重新进行邻域图计算(ov.pp.neighbors)，保留原来的邻域图的distance和connectivity。你告诉我这些单词我换成中文你能明白我在说什么吗？

**Comment by asdfasf4safasg** [comment]
是这样的，当我只用subtype的数据分析的时候，得到的stream的结果发生了改变，我用main celltype的时候不会出现这个问题

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Zehua Zeng ***@***.***>
发送时间: Saturday, July 6, 2024 12:06:44 AM
收件人: Starlitnightly/omicverse ***@***.***>
抄送: Lili ZHOU 周丽丽 ***@***.***>; Author ***@***.***>
主题: Re: [Starlitnightly/omicverse] How to perform scVelo analysis on Seurat subtypes (Issue #101)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

没太看懂你的问题，你要计算subtype在subtype上单独运行你的分析就好，例如在subtype上运行velocity。如果英文都表述不清楚那中文更难表述清楚。例如，如果你是想保留main celltype的umap结果，那你就不要重新进行邻域图计算(ov.pp.neighbors)，保留原来的邻域图的distance和connectivity。你告诉我这些单词我换成中文你能明白我在说什么吗？

―

**Comment by Starlitnightly** [comment]
What's mean of stream? What does `stream改变' mean?

**Comment by asdfasf4safasg** [comment]
![image](https://github.com/Starlitnightly/omicverse/assets/134588018/99473cf2-3490-4663-aea6-8f29d852ead2)
我是想指这个速率的箭头结果的umap在提取子集分析的时候会发生改变，但是用main celltype的umap不会出现这个问题

**Comment by Starlitnightly** [comment]
> ![image](https://private-user-images.githubusercontent.com/134588018/346278128-99473cf2-3490-4663-aea6-8f29d852ead2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDQ3NTksIm5iZiI6MTcyMDM0NDQ1OSwicGF0aCI6Ii8xMzQ1ODgwMTgvMzQ2Mjc4MTI4LTk5NDczY2YyLTM0OTAtNDY2My1hZWE2LThmMjlkODUyZWFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwOTI3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGIyODkxMTk5YjY5NDE1NGExZmI3ZWYxM2IxYzUwNmNlYTQyNDg2ZGVlYzNjN2M4ODIzYWY5ZGFkOTk5NWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MqMxHseUUz1t8uR08ixha2OVP16xJU6APAoxsHzRCDA) 我是想指这个速率的箭头结果的umap在提取子集分析的时候会发生改变，但是用main celltype的umap不会出现这个问题

我不觉得有什么区别？
<img width="933" alt="image" src="https://github.com/Starlitnightly/omicverse/assets/46667721/471cf462-146e-45cb-8c71-6ea2e95e101e">
