### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by PracticeEarnestly** [Starlitnightly/omicverse#112]
运行以下代码时出现：AttributeError: 'DataFrame' object has no attribute 'dtype'
#quantity control
adata=ov.pp.qc(adata,
              tresh={'mito_perc': 0.2, 'nUMIs': 500, 'detected_genes': 250})
#normalize and high variable genes (HVGs) calculated
adata=ov.pp.preprocess(adata,mode='shiftlog|pearson',n_HVGs=2000,)

#save the whole genes and filter the non-HVGs
adata.raw = adata
adata = adata[:, adata.var.highly_variable_features]

#scale the adata.X
ov.pp.scale(adata)

#Dimensionality Reduction
ov.pp.pca(adata,layer='scaled',n_pcs=50)

adata.obsm['X_mde']=ov.utils.mde(adata.obsm['scaled|original|X_pca'])

更新pandas后问题解决，但是提示最新版本与omicverse不兼容

**Comment by Starlitnightly** [comment]
Could you provide the version of pandas you error and success?

**Comment by PracticeEarnestly** [comment]
<img width="942" alt="image" src="https://github.com/user-attachments/assets/9595f778-d9bd-48dc-9639-9760a529be4a">
pandas version: 1.6.5

升级到最新pandas version: 2.2.2，报错消失，但是提示包不兼容

**Comment by Starlitnightly** [comment]
It seems that the new version of `anndata` has solve the problem of compatibility in `pandas>2`. 

If you want to fix this error completely, you can install `anndata==0.8` and `pandas==1.5.3`. With the latest version we need to sequence further to make sure we don't get the error.

**Comment by PracticeEarnestly** [comment]
Installing collected packages: pandas, omicverse
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.0
    Uninstalling pandas-2.0.0:
      Successfully uninstalled pandas-2.0.0
  Attempting uninstall: omicverse
    Found existing installation: omicverse 1.6.3
    Uninstalling omicverse-1.6.3:
      Successfully uninstalled omicverse-1.6.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.8.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
dask-cudf-cu12 24.8.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
dask-expr 1.1.9 requires pandas>=2, but you have pandas 1.5.3 which is incompatible.
Successfully installed omicverse-1.6.5 pandas-1.5.3
然而与cupy也有冲突，谢谢

**Comment by Starlitnightly** [comment]
The nightly version of omicverse have supported `pandas>2`

**Comment by littleacdemicwhite** [comment]
pandas==2.2.3
anndata==0.10.9
omicverse==1.6.6
仍报与楼主同样的错误
