### ISSUE TITLE
Is there a problem with numpy and sccomposite compatibility?

### ISSUE THREAD

**Issue by BelongZ** [Starlitnightly/omicverse#113]
<img width="1599" alt="截屏2024-07-24 08 51 46" src="https://github.com/user-attachments/assets/adff53e0-4ac9-4e13-8774-8b8ab24738f6">

numpy==1.23.5
omicverse==1.6.4
M1 Mac

**Comment by Starlitnightly** [comment]
You can set `doublets_method='scrublet'` instead of `sccomposite`. This issue caused by `float128`. We're checking to see if we can make it float64. @DBinary 
Zehua

**Comment by Starlitnightly** [comment]
#134
