### ISSUE TITLE
Package dependency issue during installation with conda

### ISSUE THREAD

**Issue by Aegon8719** [Starlitnightly/omicverse#120]
**Description**
When I followed the official documentation to install OmicVerse, I encountered a package dependency problem. It seemed that scikit-misc can't be installed with conda, so I turned to pip to continue and successfully installed OmicVerse in the end. I think it's still an issue which needs to be addressed.

I work in a Windows native environment.

**Screenshots**
![issue1](https://github.com/user-attachments/assets/2f133966-0028-4955-aca5-834c55746dce)
![issue2](https://github.com/user-attachments/assets/6d93ec79-94e9-4b1f-a589-7ad6e58163b7)

Thanks for your attention!

**Comment by Starlitnightly** [comment]
`scikit-misc` not support win-64, maybe you need to report this request to the `scikit-misc` author

**Comment by Aegon8719** [comment]
Okay I got it, while the official Installation Guide still claims to support native Windows. This is indeed confusing and it would be great if it could be correct. Thanks for your work.
![IMG_20240913_132524](https://github.com/user-attachments/assets/cfc03237-9e6e-4179-9356-05f298d4b8d0)
