### ISSUE TITLE
docker image require

### ISSUE THREAD

**Issue by LenisLin** [Starlitnightly/omicverse#121]
The work is truly inspiring, as it integrates multiple useful tools for bioinformatics analysis, especially RNA sequencing. However, I found managing the packages to be quite challenging. It would be greatly appreciated if you could provide a Docker image that we can apply directly. Thank you!
best regards,
lenis lin

**Comment by Starlitnightly** [comment]
Thanks for the suggestion, we'll try to configure some available docker images

Zehua

**Comment by Starlitnightly** [comment]
We now provided three docker image for different system: https://hub.docker.com/r/starlitnightly/omicverse

**Comment by LenisLin** [comment]
Thank you so much for the update, I really appreciate it!
best regards
