### ISSUE TITLE
Conflict on pertpy and omicverse 

### ISSUE THREAD

**Issue by PracticeEarnestly** [Starlitnightly/omicverse#126]
Installing collected packages: numpy, chex, scanpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  Attempting uninstall: chex
    Found existing installation: chex 0.1.83
    Uninstalling chex-0.1.83:
      Successfully uninstalled chex-0.1.83
  Attempting uninstall: scanpy
    Found existing installation: scanpy 1.9.8
    Uninstalling scanpy-1.9.8:
      Successfully uninstalled scanpy-1.9.8
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.6.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
dask-cudf-cu12 24.6.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
ktplotspy 0.2.4 requires seaborn<0.14,>=0.12, but you have seaborn 0.11.2 which is incompatible.
omicverse 1.6.5 requires numpy<1.24,>=1.22, but you have numpy 1.24.4 which is incompatible.
rapids-singlecell 0.10.7 requires scanpy>=1.10.0, but you have scanpy 1.9.6 which is incompatible.
Successfully installed chex-0.1.86 numpy-1.23.5 scanpy-1.9.6

**Comment by Starlitnightly** [comment]
@DBinary Perhaps we need to upgrade the related dependencies. The higher version of Scanpy is now compatible with Pandas 2.2. Can you test if there are any errors after updating the dependencies?

**Comment by Starlitnightly** [comment]
We have updated omicverse 1.6.6 to solve this issue.

**Comment by PracticeEarnestly** [comment]
can't wait to update to  omicverse 1.6.6 ^-^
