### ISSUE TITLE
GaussianMixture: mclust_py() got an unexpected keyword argument 'covariance_type'

### ISSUE THREAD

**Issue by muyu-fudan** [Starlitnightly/omicverse#127]
when i set method='GMM' to cluster the cells , the error occured. how can i use the Gaussian mixture model clustering
![image](https://github.com/user-attachments/assets/d9e0d2ae-236b-4b3a-abff-883a93124a03)
![image](https://github.com/user-attachments/assets/58de7531-ee21-44c4-980d-849958048987)
![image](https://github.com/user-attachments/assets/806cdf41-8e45-406b-802d-a64a3a61d37c)

**Comment by Starlitnightly** [comment]
The principle of mcluster is GMM, and the relevant parameters have been modified to similar parameters of mcluster. The old tutorial has not been updated yet, and you can check the source code to confirm the optional parameters

**Comment by yanbosmu** [comment]
any solution to this?

**Comment by yanbosmu** [comment]
ov.utils.embedding(adata,basis='X_umap',
                   color=['clusters','gmm_cluster'],
                   frameon='small',wspace=0.5)
