### ISSUE TITLE
ModuleNotFoundError: No module named 'ov.khan_logger' 

### ISSUE THREAD

**Issue by DocMonster77** [Starlitnightly/omicverse#13]
import ov
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_1434669/2229809638.py in <module>
----> 1 import ov

~/miniconda3/envs/jupyter/lib/python3.7/site-packages/ov/__init__.py in <module>
      4 from time import sleep
      5 import boto.dynamodb2
----> 6 from .khan_logger import KhanLogger
      7 
      8 __author__ = 'mattjmorris'

ModuleNotFoundError: No module named 'ov.khan_logger'

**Comment by Starlitnightly** [comment]
Hi,

"To use the `omicverse` library, please make sure to import it using the following line of code: `import omicverse as ov`. Additionally, it is recommended to use `omicverse` with Python versions 3.8 or higher."
