### ISSUE TITLE
Unexpected keyword argument "layer" in "sc.pp.pca"

### ISSUE THREAD

**Issue by fendyu** [Starlitnightly/omicverse#131]

**Comment by Starlitnightly** [comment]
You need to update scanpy>1.9

**Comment by liuxiawei** [comment]
Same problem. Recommendation of Scanpy version is necessary!

**Comment by Starlitnightly** [comment]
> Same problem. Recommendation of Scanpy version is necessary!

We will update the installation dependency of scanpy in version 1.6.7 to restrict the minimum version to 1.10, thank you for your understanding and support.

**Comment by dongmingyufu** [comment]
There seems to be a conflict between Omicverse version 1.6.7 and Scanpy version 1.10 or higher, which is causing the kernel to crash during data preprocessing and batch visualization.
adata=ov.pp.qc(adata,
              tresh={'mito_perc': 0.2, 'nUMIs': 500, 'detected_genes': 250},
              batch_key='batch')
adata=ov.pp.qc(adata,
              tresh={'mito_perc': 0.2, 'nUMIs': 500, 'detected_genes': 250},
              batch_key='batch')
