### ISSUE TITLE
 module 'omicverse.pl' has no attribute 'marker_heatmap'" 

### ISSUE THREAD

**Issue by guoguoxuan** [Starlitnightly/omicverse#135]
I met a problem about marker_heatmap, hope that can be solved, thanks!!
omicverse Version: 1.6.5, 

"name": "AttributeError",
"message": "module 'omicverse.pl' has no attribute 'marker_heatmap'",
"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 ov.pl.marker_heatmap(
      2     adata_new,
      3     marker_genes_dict,
      4     groupby='cell_type_leiden',
      5     color_map=\"RdBu_r\",
      6     use_raw=False,
      7     standard_scale=\"var\",
      8     expression_cutoff=0.0,
      9     fontsize=12,
     10     bbox_to_anchor=(7, -2),
     11     figsize=(8.5,4),
     12     spines=False,
     13     show_rownames=False,
     14     show_colnames=True,
     15 )

AttributeError: module 'omicverse.pl' has no attribute 'marker_heatmap'"

**Comment by Starlitnightly** [comment]
This is the latest version of the feature, if you need to experience it early, install `pip install git+https://github.com/Starlitnightly/omicverse.git` from github
