### ISSUE TITLE
ov.bulk.geneset_enrichment function error in Cell interaction with CellPhoneDB part

### ISSUE THREAD

**Issue by WeiQin2001** [Starlitnightly/omicverse#137]
**Run the following code:**
enr=ov.bulk.geneset_enrichment(gene_list=enrichr_genes,
                                pathways_dict=pathway_dict,
                                pvalue_type='auto',
                                organism='human')

**The errors will be found:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1445/3054788131.py in ?()
      1 #deg_genes=dds.result.loc[dds.result['sig']!='normal'].index.tolist()
----> 2 enr=ov.bulk.geneset_enrichment(gene_list=enrichr_genes,
      3                                 pathways_dict=pathway_dict,
      4                                 pvalue_type='auto',
      5                                 organism='human')

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/bulk/_Enrichment.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/bulk/_Enrichment.py) in ?(gene_list, pathways_dict, pvalue_threshold, pvalue_type, organism, description, background, outdir, cutoff)
    207             background='mmusculus_gene_ensembl'
    208         elif (organism == 'Human') or (organism == 'human') or (organism == 'hs'):
    209             background='hsapiens_gene_ensembl'
    210 
--> 211     enr = gp.enrichr(gene_list=gene_list,
    212                  gene_sets=pathways_dict,
    213                  organism=organism, # don't forget to set organism to the one you desired! e.g. Yeast
    214                  description=description,

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py) in ?(gene_list, gene_sets, organism, description, outdir, background, cutoff, format, figsize, top_term, no_plot, verbose)
    516     enr = Enrichr(gene_list, gene_sets, organism, description, outdir,
    517                   cutoff, background, format, figsize, top_term, no_plot, verbose)
    518     # set organism
    519     enr.set_organism()
--> 520     enr.run()
    521 
    522     return enr

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py) in ?(self)
    423                 shortID, res = self.get_results(genes_list)
    424                 # Remember gene set library used
    425             res.insert(0, "Gene_set", self._gs)
    426             # Append to master dataframe
--> 427             self.results = self.results.append(res, ignore_index=True)
    428             self.res2d = res
    429             if self._outdir is None: continue
    430             self._logger.info('Save file of enrichment results: Job Id:' + str(shortID))

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/generic.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/generic.py) in ?(self, name)
   6295             and name not in self._accessors
   6296             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6297         ):
   6298             return self[name]
-> 6299         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by WeiQin2001** [comment]
sorry，this error happen in the Pathway analysis with AUCell part in fact.

**Comment by WeiQin2001** [comment]
**But in Cell interaction with CellPhoneDB part, the similar error can be found :**
enr=ov.bulk.geneset_enrichment(gene_list=enrichr_genes,
                                pathways_dict=pathway_dict,
                                pvalue_type='auto',
                                organism='human')

**error:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1445/3054788131.py in ?()
      1 #deg_genes=dds.result.loc[dds.result['sig']!='normal'].index.tolist()
----> 2 enr=ov.bulk.geneset_enrichment(gene_list=enrichr_genes,
      3                                 pathways_dict=pathway_dict,
      4                                 pvalue_type='auto',
      5                                 organism='human')

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/bulk/_Enrichment.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/bulk/_Enrichment.py) in ?(gene_list, pathways_dict, pvalue_threshold, pvalue_type, organism, description, background, outdir, cutoff)
    207             background='mmusculus_gene_ensembl'
    208         elif (organism == 'Human') or (organism == 'human') or (organism == 'hs'):
    209             background='hsapiens_gene_ensembl'
    210 
--> 211     enr = gp.enrichr(gene_list=gene_list,
    212                  gene_sets=pathways_dict,
    213                  organism=organism, # don't forget to set organism to the one you desired! e.g. Yeast
    214                  description=description,

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py) in ?(gene_list, gene_sets, organism, description, outdir, background, cutoff, format, figsize, top_term, no_plot, verbose)
    516     enr = Enrichr(gene_list, gene_sets, organism, description, outdir,
    517                   cutoff, background, format, figsize, top_term, no_plot, verbose)
    518     # set organism
    519     enr.set_organism()
--> 520     enr.run()
    521 
    522     return enr

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/gseapy/enrichr.py) in ?(self)
    423                 shortID, res = self.get_results(genes_list)
    424                 # Remember gene set library used
    425             res.insert(0, "Gene_set", self._gs)
    426             # Append to master dataframe
--> 427             self.results = self.results.append(res, ignore_index=True)
    428             self.res2d = res
    429             if self._outdir is None: continue
    430             self._logger.info('Save file of enrichment results: Job Id:' + str(shortID))

[~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/generic.py](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/omicverse/Single/CellphoneDB/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/generic.py) in ?(self, name)
   6295             and name not in self._accessors
   6296             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6297         ):
   6298             return self[name]
-> 6299         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by Starlitnightly** [comment]
I have fixed this error in nightly version

**Comment by WeiQin2001** [comment]
Thank you for your great work!
