### ISSUE TITLE
Kernel crash

### ISSUE THREAD

**Issue by zhoushican** [Starlitnightly/omicverse#141]
when I run the code
```
adata.obsm['X_pca']=adata.obsm['scaled|original|X_pca']
ov.utils.embedding(adata,
                  basis='X_pca',
                  color='CST3',
                  frameon='small')
```
the Kernel crash

the platform is WSL
the code from t_preprocess_gpu.ipynb

**Comment by Starlitnightly** [comment]
It's probably a memory overflow. This issue is not related to the omicverse.

**Comment by zhoushican** [comment]
total        used        free      shared  buff/cache   available
Mem: 94Gi 2.6Gi 91Gi 86Mi 551Mi 91Gi
3k cell 94G memory

Why does memory overflow occur?
