### ISSUE TITLE
ov.utils.cluster function error

### ISSUE THREAD

**Issue by WeiQin2001** [Starlitnightly/omicverse#142]
**Single processing 部分的 Clustering space 章节**

有监督聚类部分一直运行到以下部分时出问题了：
ov.utils.cluster(adata,use_rep='scaled|original|X_pca',
                 method='GMM',n_components=21,#可以指定类群量
                 covariance_type='full',
                 tol=1e-9, max_iter=1000 )

报错如下：
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[25], line 1
----> 1 ov.utils.cluster(adata,use_rep='scaled|original|X_pca',
      2                  method='GMM',n_components=21,#可以指定类群量
      3                  covariance_type='full',
      4                  tol=1e-9, max_iter=1000 )

File [~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/utils/_cluster.py:78](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/autodl-tmp/omicverse/Single/Precessing/script/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/utils/_cluster.py#line=77), in cluster(adata, method, use_rep, random_state, n_components, **kwargs)
     76     sc.tl.louvain(adata,**kwargs)
     77 elif method=='GMM':
---> 78     mclust_py(adata, n_components=n_components,use_rep=use_rep,random_seed=random_state,**kwargs)
     79     print(f"""finished: found {n_components} clusters and added
     80 'mclust', the cluster labels (adata.obs, categorical)""")
     81 elif method=='mclust':

TypeError: mclust_py() got an unexpected keyword argument 'covariance_type'

查看源代码：“
def cluster(adata:anndata.AnnData,method:str='leiden',
            use_rep:str='X_pca',random_state:int=1024,
            n_components=None, **kwargs):
    
    if method=='leiden':
        sc.tl.leiden(adata,**kwargs)
    elif method=='louvain':
        sc.tl.louvain(adata,**kwargs)
    elif method=='GMM':
        mclust_py(adata, n_components=n_components,use_rep=use_rep,random_seed=random_state,**kwargs)
        print(f"""finished: found {n_components} clusters and added
    'mclust', the cluster labels (adata.obs, categorical)""")
    elif method=='mclust':
        mclust_py(adata, n_components=n_components,use_rep=use_rep,
                  random_seed=random_state,**kwargs)
        print(f"""finished: found {n_components} clusters and added
    'mclust', the cluster labels (adata.obs, categorical)""")
    elif method=='schist':
        try:
            import schist
        except ImportError:
            raise ImportError(
                'Please install the schist using conda `conda install -c conda-forge schist` \nor `pip install git+https://github.com/dawe/schist.git`'
            )
        schist.inference.nested_model(adata, **kwargs)

发现确实无
covariance_type， tol, max_iter等参数

**Comment by yanbosmu** [comment]
I found the same error . Any solutions?

**Comment by WeiQin2001** [comment]
NO....

**Comment by Starlitnightly** [comment]
In the latest version of the function, we have removed the `covariance_type`, `tol`, `max_iter` parameters and replaced them with parameters that we would like to use consistent with mclust, but the tutorial has not been updated yet. The use case is as follows:
```python
ov.utils.cluster(adata,use_rep='STAGATE',method='mclust',n_components=8,
                 modelNames='EEV', random_state=112,
                )
adata.obs['mclust_STAGATE'] = ov.utils.refine_label(adata, radius=50, key='mclust') 
```

**Comment by WeiQin2001** [comment]
I have understanded, thanks for your work!!!
