### ISSUE TITLE
cnmf_obj.get_results（）function error

### ISSUE THREAD

**Issue by WeiQin2001** [Starlitnightly/omicverse#143]
Consensus Non-negative Matrix factorization (cNMF)部分
当运行到cnmf_obj.get_results(adata,result_dict)部分时，出现以下报错：“
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[60], line 1
----> 1 cnmf_obj.get_results(adata,result_dict)

AttributeError: 'cNMF' object has no attribute 'get_results'

似乎没有cnmf_obj.get_results（）这个函数，但有cnmf_obj.get_results_rfc（）函数，但运行时出现以下报错：”
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[65], line 1
----> 1 cnmf_obj.get_results_rfc(adata,result_dict)

File [~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/externel/cnmf/cnmf.py:1063](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/autodl-tmp/omicverse/Single/Precessing/script/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/externel/cnmf/cnmf.py#line=1062), in cNMF.get_results_rfc(self, adata, result_dict, use_rep, cNMF_threshold)
   1061 class_array = []
   1062 for i in range(1, result_dict['usage_norm'].shape[1] + 1):
-> 1063     data = adata[adata.obs[f'cNMF_{i}'] > cNMF_threshold].obsm[use_rep].toarray()
   1064     new_array.append(data)
   1065     class_array.append(np.full(data.shape[0], i))

File [~/miniconda3/envs/omicverse/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py:161](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/autodl-tmp/omicverse/Single/Precessing/script/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py#line=160), in AlignedView.__getitem__(self, key)
    159 def __getitem__(self, key: str) -> Value:
    160     return as_view(
--> 161         _subset(self.parent_mapping[key], self.subset_idx),
    162         ElementRef(self.parent, self.attrname, (key,)),
    163     )

File [~/miniconda3/envs/omicverse/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py:213](https://a478365-a7c0-33b59a0e.cqa1.seetacloud.com:8443/jupyter/lab/tree/autodl-tmp/omicverse/Single/Precessing/script/~/miniconda3/envs/omicverse/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py#line=212), in AlignedActual.__getitem__(self, key)
    212 def __getitem__(self, key: str) -> Value:
--> 213     return self._data[key]

KeyError: 'STAGATE'

查看源代码：发现默认use_rep='STAGATE'，看不懂，求解释。。。

**Comment by Starlitnightly** [comment]
We have re-added the `get_results` function in the latest version.

**Comment by WeiQin2001** [comment]
> We have re-added the `get_results` function in the latest version.

Thank you vary mach！！！！
