### ISSUE TITLE
module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by LJZYaaa** [Starlitnightly/omicverse#145]
**Describe the bug**
HI，i really  appreciate your works in omicvese! And start to use it do some sc-rearches. But when i do the trajectory inference with VIA and scVelo as tutotail, it report as below:
 
![image](https://github.com/user-attachments/assets/427d5be8-17bb-48fa-9811-c06bd31e0049)

what's more, the follow command:
![image](https://github.com/user-attachments/assets/81b31816-5aff-4971-93e9-1a52d280d577)
![image](https://github.com/user-attachments/assets/f2292e7b-8d3e-4961-85af-db1844f348fe)

the version i use as below:
omicverse=1.6.6
numpy = 1.26.4

Any ideas on how to solve it? Thanks!

**Comment by Starlitnightly** [comment]
You need to set `gene_matrix=adata.X`, Since your adata.X is not a sparse matrix, you don't need todense to convert it
