### ISSUE TITLE
ArpackError

### ISSUE THREAD

**Issue by md26meng** [Starlitnightly/omicverse#150]
Dear Author,

I have been following your tutorials and applied them to my dataset without encountering any bugs up until the point of performing PCA. However, when I attempted to use the scaled layer for the PCA function, I encountered the following bug:

Running Chapter :
%%time
ov.pp.pca(adata,layer='scaled',n_pcs=50)
adata

Total Error notice:
---------------------------------------------------------------------------
ArpackError                               Traceback (most recent call last)
File <timed exec>:1

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/omicverse/pp/_preprocess.py:624, in pca(adata, n_pcs, layer, inplace)
    622     raise KeyError(f'Selected layer {layer} is not present. Compute it first!')
    623 if settings.mode == 'cpu':
--> 624     sc.pp.pca(adata, layer=layer,n_comps=n_pcs)
    625     adata.obsm[key + '|X_pca'] = adata.obsm['X_pca']
    626     adata.varm[key + '|pca_loadings'] = adata.varm['PCs']

File ~/.local/lib/python3.10/site-packages/scanpy/preprocessing/_pca.py:276, in pca(***failed resolving arguments***)
    272 from sklearn.decomposition import PCA
    274 svd_solver = _handle_sklearn_args(svd_solver, "PCA (with sparse input)")
--> 276 output = _pca_with_sparse(
    277     X, n_comps, solver=svd_solver, random_state=random_state
    278 )
    279 # this is just a wrapper for the results
    280 X_pca = output["X_pca"]

File ~/.local/lib/python3.10/site-packages/scanpy/preprocessing/_pca.py:432, in _pca_with_sparse(X, npcs, solver, mu, random_state)
    421     return XHmat(x) - mhmat(ones(x))
    423 XL = LinearOperator(
    424     matvec=matvec,
    425     dtype=X.dtype,
   (...)
    429     rmatmat=rmatmat,
    430 )
--> 432 u, s, v = svds(XL, solver=solver, k=npcs, v0=random_init)
    433 u, v = svd_flip(u, v)
    434 idx = np.argsort(-s)

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/sparse/linalg/_eigen/_svds.py:532, in svds(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors, solver, random_state, options)
    530 if v0 is None:
    531     v0 = random_state.standard_normal(size=(min(A.shape),))
--> 532 _, eigvec = eigsh(XH_X, k=k, tol=tol ** 2, maxiter=maxiter,
    533                   ncv=ncv, which=which, v0=v0)
    534 # arpack do not guarantee exactly orthonormal eigenvectors
    535 # for clustered eigenvalues, especially in complex arithmetic
    536 eigvec, _ = np.linalg.qr(eigvec)

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py:1697, in eigsh(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, mode)
   1695 with _ARPACK_LOCK:
   1696     while not params.converged:
-> 1697         params.iterate()
   1699     return params.extract(return_eigenvectors)

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/sparse/linalg/_eigen/arpack/arpack.py:573, in _SymmetricArpackParams.iterate(self)
    571     self._raise_no_convergence()
    572 else:
--> 573     raise ArpackError(self.info, infodict=self.iterate_infodict)

ArpackError: ARPACK error -9999: Could not build an Arnoldi factorization. IPARAM(5) returns the size of the current Arnoldi factorization. The user is advised to check that enough workspace and array storage has been allocated.

I have tried downgrading Omicverse, but the issue persists. 
I would greatly appreciate your guidance on this matter. Thank you.

**Comment by Starlitnightly** [comment]
The error you're encountering is related to the ARPACK library, which is used for solving large-scale eigenvalue problems. Specifically, it seems to be struggling with memory allocation or workspace issues when performing the Singular Value Decomposition (SVD) in the PCA function.

This issue is not related to the omicverse.
