### ISSUE TITLE
ov.pl.optim_palette() ImportError: Please install the spaco: `pip install spaco-release`.

### ISSUE THREAD

**Issue by ZHANGDAPA** [Starlitnightly/omicverse#152]
**Describe the bug**
当我按照教程文档使用ov.pl.optim_palette()函数进行Optimizing color mapping时,报错显示ImportError: Please install the spaco: `pip install spaco-release`.
我已经安装了spaco-release但是依然显示ImportError: Please install the spaco: `pip install spaco-release`.

**Screenshots**
![1](https://github.com/user-attachments/assets/e43e1e12-7284-4749-9009-ec9c78ac1d84)
![2](https://github.com/user-attachments/assets/c4b51f1e-d3ae-4e0c-85db-aaabe1a602ca)

**Comment by Starlitnightly** [comment]
Maybe you need to ask the author of `spaco`
