### ISSUE TITLE
`sccomposite` filtered out almost half  number of my cells.

### ISSUE THREAD

**Issue by colinwxl** [Starlitnightly/omicverse#155]
Is it reasonable that `sccomposite` filter out almost half of the number of my cells.
I have used `sccomposite` in `ov.pp.qc` with a batch_key='sample', and found out most of the cells was filtered out, which superized me a lot.
![QQ20240919-074856](https://github.com/user-attachments/assets/021f5539-b3b8-422d-a449-7e0db1bb9cbc)

**Comment by Starlitnightly** [comment]
That's surprising, but you can also manually check the data quality, after all, algorithms aren't perfect.

**Comment by HAH112** [comment]
> Is it reasonable that `sccomposite` filter out almost half of the number of my cells. I have used `sccomposite` in `ov.pp.qc` with a batch_key='sample', and found out most of the cells was filtered out, which superized me a lot. ![QQ20240919-074856](https://github.com/user-attachments/assets/021f5539-b3b8-422d-a449-7e0db1bb9cbc)

Hello, I'm the developer of sccomposite. Thank you for your question! 

It is indeed unexpected to remove more than half of the cells from a dataset. Typically, we expect the doublet rate to be below 40%, unless an excessive number of cells were loaded into the GEM well. While I haven't encountered cases where such a high proportion of cells are excluded in practice, it is theoretically possible—especially if the sample contains a mix of highly active (e.g., cancer) and quiescent cells. 

sccomposite is a parametric statistical method that assumes the presence of a number of stable genes (e.g., housekeeping genes) with consistent expression across cell types in the dataset. However, in rare cases where a subset of cells in the dataset exhibits extremely high expression of these stable genes, the overall gene expression distribution can become skewed, leading to an inflated doublet rate estimate. In such cases, please be cautious with sccomposite results.

Hope this helps! Let me know if you have any further questions.

Haoran
