### ISSUE TITLE
Error running ov.utils.comluster (adata, method='schist ', random_deed=112, n_jobs=1)

### ISSUE THREAD

**Issue by Zstark11** [Starlitnightly/omicverse#158]
**Describe the bug**
Error running ov.utils.comluster (adata, method='schist ', random_deed=112, n_jobs=1)

**To Reproduce**
```
import omicverse as ov
import scanpy as sc
import scvelo as scv
import pertpy as pt
import matplotlib.pyplot as plt
ov.utils.ov_plot_set()
adata=ov.read(r'/mnt/d/Python-SCRNA/test-haber/haber_count.h5ad')
adata
ov.pp.preprocess(adata,mode='shiftlog|pearson',n_HVGs=2000,)
ov.pp.scale(adata)
ov.pp.pca(adata,layer='scaled',n_pcs=50)
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=30,
               use_rep='scaled|original|X_pca', random_state=112)
# Calculate UMAP for visualization purposes
#sc.tl.umap(adata)
adata.obsm["X_mde"] = ov.utils.mde(adata.obsm["scaled|original|X_pca"])
adata
ov.utils.cluster(adata,method='schist', random_seed=112)
```
Running this step reports an error：ov.utils.cluster(adata,method='schist', random_seed=112)
Code error：joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
When solving the problem, it was found that adding the parameter 'n_jobs=1' to the function would not result in an error, but the running speed was very slow, taking nearly an hour
`ov.utils.cluster(adata,method='schist', random_seed=112,n_jobs=1)`

**Comment by Starlitnightly** [comment]
Maybe you need to ask the author of [schist](https://github.com/dawe/schist) and raise a new issue.
