### ISSUE TITLE
请求更新教程

### ISSUE THREAD

**Issue by WeiQin2001** [Starlitnightly/omicverse#160]
请问可不可以更新一下bulk2single部分的教程，里面三个部分，一个都运行不成功，Colab_Reproducibility里面的也是运行不成功。。。拜托拜托！！！

**Comment by Starlitnightly** [comment]
Thanks for pointing this out, we replaced `_stat_axis` with `index` in the latest version of `omicverse` so that pandas2 can also support `bulk2single` related functions.

Regards,
Zehua
