### ISSUE TITLE
 cannot import name '_IGraphLayout' from 'scanpy.plotting._utils'

### ISSUE THREAD

**Issue by colinwxl** [Starlitnightly/omicverse#165]
I have installed omicverse strictly follow the instruction from documentation“https://omicverse.readthedocs.io/en/latest/Installation_guild/#using-pip”.
At the end, when "import omicverse", error occurs:
![微信截图_20240925225915](https://github.com/user-attachments/assets/93c3be0a-0653-4047-b192-a0d12be4f84c)

how can I fix it?

**Comment by colinwxl** [comment]
I finally found that this is due to the scanpy publish a new release, which make `_IGraphLayout` abandoned

**Comment by Starlitnightly** [comment]
We have fixed this error in the latest version
