### ISSUE TITLE
scvi version bug

### ISSUE THREAD

**Issue by Famingzhao** [Starlitnightly/omicverse#167]
```
>>> adata_scvi=ov.single.batch_correction(adata,batch_key='sampleID',
...                            methods='scVI',n_layers=2, n_latent=30, gene_likelihood="nb")
...Begin using scVI to correct batch effect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniconda3/envs/ov/lib/python3.10/site-packages/omicverse/single/_batch.py", line 91, in batch_correction
    scvi.model.SCVI.setup_anndata(adata, layer="counts", batch_key=batch_key)
  File "miniconda3/envs/ov/lib/python3.10/site-packages/scvi/model/_scvi.py", line 218, in setup_anndata
    adata_manager = AnnDataManager(fields=anndata_fields, setup_method_args=setup_method_args)
  File "miniconda3/envs/ov/lib/python3.10/site-packages/scvi/data/_manager.py", line 94, in __init__
    _constants._SCVI_VERSION_KEY: scvi.__version__,
AttributeError: module 'scvi' has no attribute '__version__'
```
May be the scvi version problem.

**Comment by Famingzhao** [comment]
![image](https://github.com/user-attachments/assets/5591fe85-c377-4666-a1df-0a00a33716ac)

Following the tutorial notebook.

**Comment by Starlitnightly** [comment]
> ![image](https://private-user-images.githubusercontent.com/79517714/375077883-5591fe85-c377-4666-a1df-0a00a33716ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MDU1NDYsIm5iZiI6MTcyODUwNTI0NiwicGF0aCI6Ii83OTUxNzcxNC8zNzUwNzc4ODMtNTU5MWZlODUtYzM3Ny00NjY2LWExZGYtMGEwMGEzMzcxNmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDIwMjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NDVhYjIwOTdlZDhmZGU1MGQ0ZDUzYWM3MWEyZjE1NWI3ZjkzN2EzNzA2MmEyNzI1NTA0NTc4N2IzMmY3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BlJCo6mVqmprsllKLwgeKtXn0r9pjJKh0p3CdqKxkkY)
> 
> Following the tutorial notebook.

What I want to say is that there might be an issue with the way you installed scvi. Perhaps you could use pip install -U scvi-tools after installing omicverse. It's possible that you used pip install scvi, which resulted in installing an older version of scvi.

Sincerely,
Zehua

**Comment by Starlitnightly** [comment]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/d46f3d1b-d030-481b-bfd1-af5bb28ffac6">

You can see that in my environment, scvi has the `__version__` parameter.

**Comment by DBinary** [comment]
I have successfully tested the installation of scvi within the omicverse environment. 

To ensure that scvi can be imported correctly, please install scvi version 1.1.2 along with its dependencies, jax and jaxlib, at versions 0.4.13.

Sincerely,
Lei
