### ISSUE TITLE
Update gseapy 

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [Starlitnightly/omicverse#170]
There is a dependency for gseapy==0.10.8 and the latest version of gseapy is 1.13. This makes it so that gseapy and omicverse can't really be installed on the same environment which is a shame since these tools complement each other. So much has changed in gseapy that using the version 0.10.8 is counterproductive; I'd suggest replacing gseapy with the latest version and change whatever needs to be changed in omicverse to be compatible with gseapy 1.13 instead

**Comment by Starlitnightly** [comment]
I remember i have removed the dependency of gseapy in 1.6.7 of omicverse

**Comment by LeafLight** [comment]
I am using omicverse 1.6.10, this issue is not well addressed. 
in `omicverse/omicverse/bulk/_Enrichment.py` line 420, there is `from gseapy.plot import GSEAPlot`, which should be imported from `..external` instead
