### ISSUE TITLE
ov.single.cellfategenie function error

### ISSUE THREAD

**Issue by WeiQin2001** [Starlitnightly/omicverse#175]
run the code of "5. Timing-associated genes analysis with cellfategenie", the error will be found :

![image](https://github.com/user-attachments/assets/4f703618-2857-4293-b0cf-36a5dacdfada)

but the _cellfategenie.py is there but not used rightly

![image](https://github.com/user-attachments/assets/e6b4cc20-cdd7-4ba9-9647-200f9e6bf309)

**Comment by WeiQin2001** [comment]
This part has been updated by the author, the new function is called Fate，you can try ov.single.fate（）

**Comment by Starlitnightly** [comment]
The latest tutorial could be found in https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_cellfate_gene/
