### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric' when using SCSA

### ISSUE THREAD

**Issue by jung233** [Starlitnightly/omicverse#176]
Very useful tool! But I encountered a problem that I can't solve.
## Error details:
```
ModuleNotFoundError Traceback (most recent call last)
Cell In[31], line 1
----> 1 anno=scsa.cell_anno(clustertype='leiden',
2 cluster='all',rank_rep=True)

File ~/miniconda3/envs/omicverse_gpu/lib/python3.10/site-packages/omicverse/single/_anno.py:464, in pySCSA.cell_anno(self, clustertype, cluster, rank_rep)
461 print('...Auto annotate cell')
463 p = Process()
--> 464 p.run_cmd_p(foldchange=self.foldchange,
465 weight=self.weight,
466 pvalue=self.pvalue,
467 tissue=self.tissue,
468 species=self.species,
469 target=self.target,
470 norefdb=self.norefdb,
471 MarkerDB=None,
472 db=self.model_path,
473 noprint=self.noprint,
474 input="temp/rna.csv",
475 output=self.output,
476 source="scanpy",
477 cluster=cluster,
478 fc=self.foldchange,
479 outfmt=self.outfmt,
480 celltype=self.celltype,
481 Gensymbol=self.Gensymbol,
482 list_tissue=self.list_tissue,
483 cellrange=self.cellrange)
486 result=pd.read_csv('temp/rna_anno.txt',sep='\t')
487 self.result=result

File ~/miniconda3/envs/omicverse_gpu/lib/python3.10/site-packages/omicverse/single/_SCSA.py:1385, in Process.run_cmd_p(self, foldchange, weight, pvalue, tissue, species, target, norefdb, MarkerDB, db, noprint, input, output, source, cluster, fc, outfmt, celltype, Gensymbol, list_tissue, cellrange)
1379 rdbname=Process.check_db(db)
1380 anno = Annotator(foldchange,weight,
1381 pvalue,tissue,species,
1382 target,norefdb,MarkerDB,db,
1383 noprint,input,output,source,cluster,fc,
1384 outfmt,celltype,Gensymbol,list_tissue,cellrange)
-> 1385 anno.load_pickle_module(rdbname)
1386 outs=anno.run_detail_cmd()
1387 print("#Cluster","Type","Celltype","Score","Times")

File ~/miniconda3/envs/omicverse_gpu/lib/python3.10/site-packages/omicverse/single/_SCSA.py:1160, in Annotator.load_pickle_module(self, db)
1158 handler = gzip.open(db,"rb")
1159 self.gos = load(handler)
-> 1160 self.human_gofs = load(handler)
1161 self.mouse_gofs = load(handler)
1162 self.cmarkers = load(handler)

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'
```
## Enviroment:
```
Package                   Version        Editable project location
------------------------- -------------- --------------------------------------------------------------------------------------------------
absl-py                   2.1.0
adjustText                1.2.0
aiohappyeyeballs          2.4.2
aiohttp                   3.10.6
aiosignal                 1.3.1
anndata                   0.10.9
annoy                     1.17.3
anyio                     4.6.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
array_api_compat          1.8
arrow                     1.3.0
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     24.2.0
autocommand               2.2.2
autograd                  1.7.0
autograd-gamma            0.5.0
backports.tarfile         1.2.0
beautifulsoup4            4.12.3
biopython                 1.84
bleach                    6.1.0
bokeh                     3.5.2
boltons                   24.0.0
cachetools                5.5.0
certifi                   2024.8.30
cffi                      1.17.1
cfgv                      3.4.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorcet                  3.1.0
comm                      0.2.2
contourpy                 1.3.0
ctxcore                   0.2.0
cucim-cu12                24.4.0
cuda-python               12.6.0
cudf-cu12                 24.4.1
cugraph-cu12              24.4.0
cuml-cu12                 24.4.0
cuproj-cu12               24.4.0
cupy-cuda12x              13.3.0
cuspatial-cu12            24.4.0
cuvs-cu12                 24.4.0
cuxfilter-cu12            24.4.1
cycler                    0.12.1
Cython                    3.0.11
cytoolz                   0.12.3
dask                      2024.1.1
dask-cuda                 24.4.0
dask-cudf-cu12            24.4.1
dask-expr                 0.4.0
datashader                0.16.3
DateTime                  5.5
debugpy                   1.8.6
decorator                 5.1.1
defusedxml                0.7.1
Deprecated                1.2.14
dill                      0.3.8
distlib                   0.3.8
distributed               2024.1.1
einops                    0.8.0
exceptiongroup            1.2.2
executing                 2.1.0
fastjsonschema            2.20.0
fastrlock                 0.8.2
fcsparser                 0.2.8
filelock                  3.16.1
fonttools                 4.54.1
formulaic                 1.0.2
fqdn                      1.5.1
frozendict                2.4.4
frozenlist                1.4.1
fsspec                    2024.9.0
future                    1.0.0
gdown                     5.2.0
geopandas                 1.0.1
graphtools                1.5.3
grpcio                    1.66.1
h5py                      3.12.1
harmonypy                 0.0.10
holoviews                 1.19.1
huggingface-hub           0.25.1
identify                  2.6.1
idna                      3.10
igraph                    0.11.6
imageio                   2.35.1
importlib_metadata        8.5.0
importlib_resources       6.4.0
inflect                   7.3.1
interface-meta            1.3.0
ipykernel                 6.29.5
ipython                   8.27.0
ipywidgets                8.1.5
isoduration               20.11.0
jaraco.collections        5.1.0
jaraco.context            5.3.0
jaraco.functools          4.0.1
jaraco.text               3.12.1
jax                       0.4.33
jaxlib                    0.4.33
jaxopt                    0.8.3
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter_client            8.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter_server            2.14.2
jupyter_server_proxy      4.4.0
jupyter_server_terminals  0.5.3
jupyterlab_pygments       0.3.0
jupyterlab_widgets        3.0.13
kiwisolver                1.4.7
ktplotspy                 0.2.4
lazy_loader               0.4
legacy-api-wrap           1.4
leidenalg                 0.10.2
lifelines                 0.29.0
linkify-it-py             2.0.3
llvmlite                  0.43.0
locket                    1.0.0
loompy                    3.0.7
Markdown                  3.7
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.6.3
matplotlib-inline         0.1.7
mdit-py-plugins           0.4.2
mdurl                     0.1.2
mellon                    1.4.3
metatime                  1.3.0
mistune                   3.0.2
mizani                    0.9.3
ml_dtypes                 0.5.0
mofax                     0.3.6
more-itertools            10.3.0
mpmath                    1.3.0
msgpack                   1.1.0
multidict                 6.1.0
multipledispatch          1.0.0
multiprocess              0.70.16
natsort                   8.4.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
ncls                      0.0.68
nest_asyncio              1.6.0
networkx                  3.3
nodeenv                   1.9.1
numba                     0.60.0
numpy                     1.26.4
numpy-groupies            0.11.2
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.6.68
nvidia-nvtx-cu12          12.1.105
nvtx                      0.2.10
omicverse                 1.6.7
opt_einsum                3.4.0
overrides                 7.7.0
packaging                 24.1
palantir                  1.3.3
pandas                    2.2.1
pandocfilters             1.5.1
panel                     1.5.0
param                     2.1.1
parso                     0.8.4
partd                     1.4.2
patsy                     0.5.6
pexpect                   4.9.0
phate                     1.0.11
pickleshare               0.7.5
pillow                    10.4.0
pip                       24.2
platformdirs              4.3.6
plotly                    5.24.1
plotnine                  0.12.4
pre-commit                3.8.0
progressbar2              4.5.0
prometheus_client         0.21.0
prompt_toolkit            3.0.48
protobuf                  4.25.5
psutil                    6.0.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pyarrow                   14.0.2
pycparser                 2.22
pyct                      0.5.0
pydeseq2                  0.4.11
pygam                     0.8.0
Pygments                  2.18.0
PyGSP                     0.5.1
pylibcugraph-cu12         24.4.0
pylibraft-cu12            24.4.0
pynndescent               0.5.13
pynvjitlink-cu12          0.3.0
pynvml                    11.4.1
pyogrio                   0.9.0
pyparsing                 3.1.4
pyproj                    3.6.1
pyranges                  0.1.2
PySocks                   1.7.1
python-circos             0.3.0
python-dateutil           2.9.0
python-dotplot            0.0.1
python-json-logger        2.0.7
python-utils              3.9.0
pytz                      2024.2
pyviz_comms               3.0.3
PyYAML                    6.0.2
pyzmq                     26.2.0
raft-dask-cu12            24.4.0
rapids-dask-dependency    24.4.1
rapids_singlecell         0.10.8
referencing               0.35.1
regex                     2024.9.11
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.8.1
rmm-cu12                  24.4.0
rpds-py                   0.20.0
ruff                      0.6.8
s-gd2                     1.8.1
safetensors               0.4.5
scanpy                    1.10.3
scikit-image              0.22.0
scikit-learn              1.5.2
scikit-misc               0.5.1
scipy                     1.11.4
scprep                    1.1.0
scrublet                  0.2.3
scvelo                    0.3.2
seaborn                   0.13.2
SEACells                  0.3.3          
Send2Trash                1.8.3
session_info              1.0.0
setuptools                75.1.0
shapely                   2.0.6
simpervisor               1.0.0
six                       1.16.0
sniffio                   1.3.1
sorted-nearest            0.0.39
sortedcontainers          2.4.0
soupsieve                 2.6
stack-data                0.6.2
statsmodels               0.14.3
stdlib-list               0.10.0
sympy                     1.13.3
tabulate                  0.9.0
tasklogger                1.2.0
tblib                     3.0.0
tenacity                  9.0.0
tensorboard               2.18.0
tensorboard-data-server   0.7.2
termcolor                 2.4.0
terminado                 0.18.1
texttable                 1.7.0
threadpoolctl             3.5.0
tifffile                  2024.9.20
tinycss2                  1.3.0
tokenizers                0.20.0
tomli                     2.0.1
toolz                     0.12.1
torch                     2.4.1
torch-geometric           2.6.1
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
transformers              4.45.1
treelite                  4.1.2
triton                    3.0.0
typeguard                 4.3.0
types-python-dateutil     2.9.0.20240906
typing_extensions         4.12.2
tzdata                    2024.2
uc-micro-py               1.0.3
ucx-py-cu12               0.37.0
umap-learn                0.5.6
uri-template              1.3.0
urllib3                   2.2.3
virtualenv                20.26.5
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.0.4
wheel                     0.44.0
widgetsnbextension        4.0.13
wrapt                     1.16.0
xarray                    2024.9.0
xyzservices               2024.9.0
yarl                      1.13.0
zict                      3.0.0
zipp                      3.20.2
zope.interface            7.0.3
```
## Some attempts
According to https://github.com/bioinfo-ibms-pumc/SCSA/issues/29
It seems that pandas needs to be downgraded, but this will cause incompatibility with other packages 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
dask-cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
dask-expr 0.4.0 requires pandas>=2, but you have pandas 1.5.3 which is incompatible.
lifelines 0.29.0 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.
xarray 2024.9.0 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.
```
Similar question: #168 

Thanks for your help!

**Comment by WeiQin2001** [comment]
pip install pandas ==1.5.3 can solve this SCSA error

**Comment by jung233** [comment]
Thanks for your reply, but as I pointed out in "Some attempts", it will cause other dependency issues.

**Comment by fredsamhaak** [comment]
Thanks for your instructions, here are my codes:

In pandas 1.5.3 environment:
`import gzip
import pickle
import os
import pandas as pd

# Function to save variables as plain text files or CSV
def save_variable_as_txt(name, var):
    """
    Save any variable as a plain text file or CSV if it's a DataFrame.
    """
    os.makedirs('./db2plaintext', exist_ok=True)  # Create directory if it doesn't exist
    
    if isinstance(var, dict):  # For dictionaries, save as key-value pairs
        with open(f'./db2plaintext/{name}.txt', 'w') as f:
            for key, value in var.items():
                f.write(f"{key}: {value}\n")
    
    elif isinstance(var, list):  # For lists, save one item per line
        with open(f'./db2plaintext/{name}.txt', 'w') as f:
            for item in var:
                f.write(f"{item}\n")
    
    elif isinstance(var, pd.DataFrame):  # For DataFrames, save as CSV
        var.to_csv(f'./db2plaintext/{name}.csv', index=False)
    
    else:  # For other types, save as string representation
        with open(f'./db2plaintext/{name}.txt', 'w') as f:
            f.write(str(var))
    
    print(f"{name} saved.")

# Function to save DataFrames in a list as separate CSV files
def save_list_as_csv(list_name, data_list):
    """
    Save each DataFrame in the list as a separate CSV file.
    """
    os.makedirs('./db2plaintext', exist_ok=True)  # Create directory if it doesn't exist
    
    for i, df in enumerate(data_list):
        df.to_csv(f'./db2plaintext/{list_name}_{i + 1}.csv', index=False)
    
    print(f"{list_name} dataframes saved as separate CSV files.")

# Function to read the db file in Pandas 1.5.3 environment and save all variables
def read_and_save_db_pandas1_as_txt(db_file):
    """
    Read the db file and save all variables, including lists, in plain text (*.txt) format.
    """
    with gzip.open(db_file, 'rb') as f:
        gos = pickle.load(f)
        human_gofs = pickle.load(f)  # Expecting a list of 3 DataFrames
        mouse_gofs = pickle.load(f)  # Expecting a list of 3 DataFrames
        cmarkers = pickle.load(f)
        smarkers = pickle.load(f)
        snames = pickle.load(f)
        ensem_hgncs = pickle.load(f)
        ensem_mouse = pickle.load(f)

    # Save each variable as a plain text file
    save_variable_as_txt('gos', gos)
    save_variable_as_txt('cmarkers', cmarkers)
    save_variable_as_txt('smarkers', smarkers)
    save_variable_as_txt('snames', snames)
    save_variable_as_txt('ensem_hgncs', ensem_hgncs)
    save_variable_as_txt('ensem_mouse', ensem_mouse)

    # Save human_gofs and mouse_gofs as separate CSV files
    save_list_as_csv('human_gofs', human_gofs)
    save_list_as_csv('mouse_gofs', mouse_gofs)

    print("All variables saved in './db2plaintext'.")

# Call the function
read_and_save_db_pandas1_as_txt(ori_db_file)
`

In pandas 2.x environment:
`import pandas as pd
import gzip
import pickle
import os

# Function to load variables from the plain text (*.txt) files and CSV files
def load_from_txt_and_csv():
    """
    Load variables from plain text and CSV files in the './db2plaintext' directory.
    """
    # Load dictionary-like text files (key-value pairs)
    gos = {}
    with open('./db2plaintext/gos.txt', 'r') as f:
        for line in f:
            key, value = line.strip().split(': ', 1)
            gos[key] = value

    ensem_hgncs = {}
    with open('./db2plaintext/ensem_hgncs.txt', 'r') as f:
        for line in f:
            key, value = line.strip().split(': ', 1)
            ensem_hgncs[key] = value

    ensem_mouse = {}
    with open('./db2plaintext/ensem_mouse.txt', 'r') as f:
        for line in f:
            key, value = line.strip().split(': ', 1)
            ensem_mouse[key] = value

    snames = {}
    with open('./db2plaintext/snames.txt', 'r') as f:
        for line in f:
            key, value = line.strip().split(': ', 1)
            snames[key] = value

    # Load lists from CSV files
    human_gofs = [pd.read_csv(f'./db2plaintext/human_gofs_{i + 1}.csv') for i in range(3)]
    mouse_gofs = [pd.read_csv(f'./db2plaintext/mouse_gofs_{i + 1}.csv') for i in range(3)]

    # Load DataFrame-like text files (CSV formatted but saved as .txt)
    cmarkers = pd.read_csv('./db2plaintext/cmarkers.csv')
    smarkers = pd.read_csv('./db2plaintext/smarkers.csv')

    return (gos, ensem_hgncs, ensem_mouse, snames, cmarkers, smarkers, human_gofs, mouse_gofs)

# Function to save the loaded variables to a new pickle file
def save_to_pickle(db_file, gos, ensem_hgncs, ensem_mouse, snames, cmarkers, smarkers, human_gofs, mouse_gofs):
    """
    Save the loaded variables to a new db file as a pickle.
    """
    with gzip.open(db_file, "wb") as handler:
        pickle.dump(gos, handler)
        pickle.dump(human_gofs, handler)
        pickle.dump(mouse_gofs, handler)
        pickle.dump(cmarkers, handler)
        pickle.dump(smarkers, handler)
        pickle.dump(snames, handler)
        pickle.dump(ensem_hgncs, handler)
        pickle.dump(ensem_mouse, handler)

    print(f"Database saved to {db_file} in pickle format.")

# Example usage
def main():
    # Load variables from txt and CSV files
    gos, ensem_hgncs, ensem_mouse, snames, cmarkers, smarkers, human_gofs, mouse_gofs = load_from_txt_and_csv()
    
    # Save to a new pickle file
    save_to_pickle('new_db_file.db', gos, ensem_hgncs, ensem_mouse, snames, cmarkers, smarkers, human_gofs, mouse_gofs)

# Run the main function
main()
`

The new db file will be saved. But there is an issue when I run SCSA:
`{
	"name": "KeyError",
	"message": "2",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/indexes/base.py:3790, in Index.get_loc(self, key)
   3789 try:
-> 3790     return self._engine.get_loc(casted_key)
   3791 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 2

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[9], line 13
      2 print(f'Annotate based on database: {target}\
######')
      3 scsa = ov.single.pySCSA(adata=adata,
      4                     foldchange=1.5,
      5                     pvalue=0.01,
   (...)
     10                     model_path=SCSAMODEL
     11 )
---> 13 anno = scsa.cell_anno(clustertype=CLUSTERTYPE,
     14             cluster='all', rank_rep=True)
     16 key = f'scsa_celltype_{target}'
     17 scsa.cell_auto_anno(adata, key=key)

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/single/_anno.py:464, in pySCSA.cell_anno(self, clustertype, cluster, rank_rep)
    461 print('...Auto annotate cell')
    463 p = Process()
--> 464 p.run_cmd_p(foldchange=self.foldchange,
    465             weight=self.weight,
    466             pvalue=self.pvalue,
    467             tissue=self.tissue,
    468             species=self.species,
    469             target=self.target,
    470             norefdb=self.norefdb,
    471             MarkerDB=None,
    472             db=self.model_path,
    473             noprint=self.noprint,
    474             input=\"temp/rna.csv\",
    475             output=self.output,
    476             source=\"scanpy\",
    477             cluster=cluster,
    478             fc=self.foldchange,
    479             outfmt=self.outfmt,
    480             celltype=self.celltype,
    481             Gensymbol=self.Gensymbol,
    482             list_tissue=self.list_tissue,
    483             cellrange=self.cellrange)
    486 result=pd.read_csv('temp/rna_anno.txt',sep='\\t')
    487 self.result=result

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/single/_SCSA.py:1386, in Process.run_cmd_p(self, foldchange, weight, pvalue, tissue, species, target, norefdb, MarkerDB, db, noprint, input, output, source, cluster, fc, outfmt, celltype, Gensymbol, list_tissue, cellrange)
   1380 anno = Annotator(foldchange,weight,
   1381          pvalue,tissue,species,
   1382          target,norefdb,MarkerDB,db,
   1383          noprint,input,output,source,cluster,fc,
   1384          outfmt,celltype,Gensymbol,list_tissue,cellrange)
   1385 anno.load_pickle_module(rdbname)
-> 1386 outs=anno.run_detail_cmd()
   1387 print(\"#Cluster\",\"Type\",\"Celltype\",\"Score\",\"Times\")
   1388 for o in outs:

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/single/_SCSA.py:1282, in Annotator.run_detail_cmd(self)
   1280     else:
   1281         self.read_user_markers('ensemblID')
-> 1282     outs = self.calcu_scanpy_group(self.input,self.Gensymbol)
   1283     return outs
   1284 elif self.source.lower() == \"scran\":

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/single/_SCSA.py:666, in Annotator.calcu_scanpy_group(self, expfile, hgvc)
    664     if not trownames:continue
    665     other_gene_names = set(tcolnames)
--> 666     self.deal_with_badtype(cname,other_gene_names,colnames)
    667 elif self.target.lower() == \"cancersea\":
    668     tfc,trownames,trownum,tcolnames,tcolnum = self.get_cell_gene_names(otherexps,self.smarkers,ofid,gcol,ccol,'other')

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/single/_SCSA.py:276, in Annotator.deal_with_badtype(self, cname, other_gene_names, colnames)
    274 if self.noprint == False:
    275     print(o)
--> 276 outs = self.do_go_annotation(f,fset,bset,cname,names[i][0])
    277 if outs.size == 0:continue
    278 if all_outs.size == 0:

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/omicverse/single/_SCSA.py:141, in Annotator.do_go_annotation(self, gof, fore, back, cname, gtype)
    139 def do_go_annotation(self,gof,fore,back,cname,gtype):
    140     \"\"\"return go annotation with significance tag\"\"\"
--> 141     fil = gof[2].map(lambda value: len(set([value]) & fore) > 0)
    142     fgnames = gof[fil].groupby(by=4)[2].unique()
    143     bfil = gof[2].map(lambda value: len(set([value]) & back) > 0)

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/frame.py:3896, in DataFrame.__getitem__(self, key)
   3894 if self.columns.nlevels > 1:
   3895     return self._getitem_multilevel(key)
-> 3896 indexer = self.columns.get_loc(key)
   3897 if is_integer(indexer):
   3898     indexer = [indexer]

File ~/miniconda3/envs/omicverse/lib/python3.10/site-packages/pandas/core/indexes/base.py:3797, in Index.get_loc(self, key)
   3792     if isinstance(casted_key, slice) or (
   3793         isinstance(casted_key, abc.Iterable)
   3794         and any(isinstance(x, slice) for x in casted_key)
   3795     ):
   3796         raise InvalidIndexError(key)
-> 3797     raise KeyError(key) from err
   3798 except TypeError:
   3799     # If we have a listlike key, _check_indexing_error will raise
   3800     #  InvalidIndexError. Otherwise we fall through and re-raise
   3801     #  the TypeError.
   3802     self._check_indexing_error(key)

KeyError: 2"
}`

Would you please give me some advice? Thank you very much in advance.

All the best,
He

**Comment by sparsepenn** [comment]
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'

I've come across a similar issue. I was wondering if anyone might have an updated solution?

**Comment by H1207953831** [comment]
由于比较着急，我就不翻译了，直接用中文吧
我尝试修改_SCSA.py的源代码，就没有出现'pandas.core.indexes.numeric'的报错；
```python
    def load_pickle_module(self,db):
        """read whole database"""
        handler = gzip.open(db,"rb")
        #self.gos = load(handler)
        #self.human_gofs = load(handler)
        #self.mouse_gofs = load(handler)
        #self.cmarkers = load(handler)
        #self.smarkers = load(handler)
        #self.snames = load(handler)
        #self.ensem_hgncs = load(handler)
        #self.ensem_mouse = load(handler)

        self.gos = pd.read_pickle(handler)
        self.human_gofs = pd.read_pickle(handler)
        self.mouse_gofs = pd.read_pickle(handler)
        self.cmarkers = pd.read_pickle(handler)
        self.smarkers = pd.read_pickle(handler)
        self.snames = pd.read_pickle(handler)
        self.ensem_hgncs = pd.read_pickle(handler)
        self.ensem_mouse = pd.read_pickle(handler)
```
在下面的一两行的位置上有一段代码
```python
self.cmarkers = self.cmarkers[~self.cmarkers['cellName'].isin(fil)]
```
根据这段代码提示，cmarkers属性中，必须要存在`cellName`这一个字段
然而，我使用两种方法，`load()`以及`pd.read_pickle()`均未发现所给的db文件中存在有`cellName`这一字段。
导入的db文件分别有`pySCSA_2023_v2_plus.db`，`pySCSA_2023.db`，`whole_v2.db`。
不但如此，在接下去要运行一个步骤中，还存在多个必须的字段，也就是`tissueType`,`cellType`,`speciesType`等，这些字段均无法在上述db文件中找到。

可以发现的是，self.cmarkers等属性，都是源自于所提供的db文件，因此我认为可能是db文件有问题，为此我还从不同的途径下载db文件，发现结果还是一样。

**Comment by Starlitnightly** [comment]
@fredsamhaak  Thanks to your contribution, we've released an updated SCSA database that can be loaded on pandas>2! And the omicverse version needs to be greater than 1.6.9 to load the database correctly! The database can be downloaded from [Google Drive](https://drive.google.com/file/d/1gg2m-edV2Jff8krWovsNb0jxv8A-DFol/view?usp=drive_link) and [百度云](https://pan.baidu.com/s/1o7w48z8_5QRlUAjz9auUQg?pwd=j6mp). 

Best,
Zehua
