### ISSUE TITLE
can't plot the figure

### ISSUE THREAD

**Issue by asdChenJin** [Starlitnightly/omicverse#18]
When I use the Scanpy to plot a figure in omicverse's enviroment, it didn't show me the figure, it's nothing.
There have many functionts not work.
![image](https://github.com/Starlitnightly/omicverse/assets/33625968/c97f1953-fbe2-4fe8-ada6-d7f402a310ee)
![image](https://github.com/Starlitnightly/omicverse/assets/33625968/94b3def1-7e42-4b18-b7fd-3b0e49f3d512)

**Comment by Starlitnightly** [comment]
Hi,

you can add  %matplotlib inline in the cells of Jupyter-notebook after import

**Comment by asdChenJin** [comment]
I get it, Thanks!

**Comment by asdChenJin** [comment]
I get it.
Thanks!

> Hi,
> 
> you can add %matplotlib inline in the cells of Jupyter-notebook after import
