### ISSUE TITLE
scipy version adaptation issues

### ISSUE THREAD

**Issue by Zstark11** [Starlitnightly/omicverse#189]
I need scipy version 1.10.0 when doing VIA trajectory inference.
Because if my scipy version is 1.11.4 when I run
```
v0 = ov.single.pyVIA(adata=adata,adata_key='X_pca',adata_ncomps=80, basis='tsne',
                         clusters='clusters',knn=30,random_seed=4,root_user=[4823],)
v0.run()
```
will report an error
`ValueError: mismatching number of index arrays for shape; got 0, expected 2`

However, version 1.10.0 of scipy will give an error when performing differential expression analysis of cells
when I run
`dds.deg_analysis(treatment_groups,control_groups,method='ttest')`
will report an error
`ImportError: cannot import name 'false_discovery_control' from 'scipy.stats' (/home/zouguoyin/anaconda3/envs/py3.10/lib/python3.10/site-packages/scipy/stats/__init__.py)
`

Hopefully the scipy version will be unified

**Comment by DBinary** [comment]
I have the similar bug with you, we will fix this bug quickly.
And actually, this bug will not affect the subsequent analyses, the relevant results have been calculated and stored before triggering the bug.

Best wishes,
Lei
