### ISSUE TITLE
Unable to draw PCA

### ISSUE THREAD

**Issue by Dexterssssss** [Starlitnightly/omicverse#197]
The code I cun：
import matplotlib.pyplot as plt
fig,axes=plt.subplots(1,2,figsize=(8,4))
ov.utils.embedding(adata,
                basis='scaled|original|X_pca',frameon='small',
                color='MS4A1',show=False,ax=axes[0])
ov.utils.embedding(adata,
                basis='counts|original|X_pca',frameon='small',
                color='MS4A1',show=False,ax=axes[1])

error：
AttributeError: 'AnchoredSizeLocator' object has no attribute '_update_offset_func'
[/usr/local/lib/python3.10/dist-packages/mpl_toolkits/axes_grid1/inset_locator.py](https://localhost:8080/#) in __call__(self, ax, renderer)
     73 
     74         fontsize = renderer.points_to_pixels(self.prop.get_size_in_points())
---> 75         self._update_offset_func(renderer, fontsize)
     76 
     77         width, height, xdescent, ydescent = self.get_extent(renderer)

AttributeError: 'AnchoredSizeLocator' object has no attribute '_update_offset_func'

enviroment：
colab

**Comment by Starlitnightly** [comment]
Could you provide the version of `matplotlib`

**Comment by Dexterssssss** [comment]
It is 3.8.0.

**Comment by Starlitnightly** [comment]
> It is 3.8.0.

Could you try `pip install matplotlib==3.6.3`

**Comment by Dexterssssss** [comment]
Unfortunately, the same error still occurs.
I suspect this may be due to the colab platform?
Because I'm on other platforms (such as autodl), using version 3.6.3 of matplotlib, and I don't have this problem.

**Comment by Dexterssssss** [comment]
> > It is 3.8.0.
> 
> Could you try `pip install matplotlib==3.6.3`

Unfortunately, the same error still occurs.
I suspect this may be due to the colab platform?
Because I'm on other platforms (such as autodl), using version 3.6.3 of matplotlib, and I don't have this problem.
