### ISSUE TITLE
Can Not get marker genes for a given cell type

### ISSUE THREAD

**Issue by Dexterssssss** [Starlitnightly/omicverse#199]
Code：
marker_dict = ov.single.get_celltype_marker(adata,
                                            clustertype='scsa_celltype_cellmarker')

Error：
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_50/3544009804.py in ?()
      1 # 获取指定细胞类型的marker基因
----> 2 marker_dict = ov.single.get_celltype_marker(adata,
      3                                             clustertype='scsa_celltype_cellmarker')
      4 
      5 marker_dict.keys()

/opt/conda/lib/python3.10/site-packages/omicverse/single/_anno.py in ?(adata, clustertype, log2fc_min, scores_type, pval_cutoff, rank, key, method, foldchange, topgenenumber)
    332         cell_marker_dict={}
    333         if rank==False:
    334             sc.tl.rank_genes_groups(adata, clustertype, method=method)
    335         for celltype in celltypes:
--> 336             degs = sc.get.rank_genes_groups_df(adata, group=celltype, key=key, log2fc_min=log2fc_min, 
    337                                             pval_cutoff=pval_cutoff)
    338             foldp=np.histogram(degs[scores_type])
    339             if foldchange is None:

/opt/conda/lib/python3.10/site-packages/scanpy/get/get.py in ?(adata, group, key, pval_cutoff, log2fc_min, log2fc_max, gene_symbols)
     77 
     78     d = [pd.DataFrame(adata.uns[key][c])[group] for c in colnames]
     79     d = pd.concat(d, axis=1, names=[None, "group"], keys=colnames)
     80     if Version(pd.__version__) >= Version("2.1"):
---> 81         d = d.stack(level=1, future_stack=True).reset_index()
     82     else:
     83         d = d.stack(level=1).reset_index()
     84     d["group"] = pd.Categorical(d["group"], categories=group)

/opt/conda/lib/python3.10/site-packages/pandas/core/frame.py in ?(self, level, dropna, sort, future_stack)

ImportError: cannot import name 'stack_v3' from 'pandas.core.reshape.reshape' (/opt/conda/lib/python3.10/site-packages/pandas/core/reshape/reshape.py)

**Comment by Starlitnightly** [comment]
Could you provide the version of `pandas` and `scanpy`

**Comment by Dexterssssss** [comment]
Thank you very much for your reply, I changed the pandas version to 1.5.3 and this error no longer occurs.
My scanpy version is 1.10.3.
