### ISSUE TITLE
ov.space.pySTAligner:AttributeError: 'ArrayView' object has no attribute 'todense'

### ISSUE THREAD

**Issue by GhostInTheShellwjc** [Starlitnightly/omicverse#209]
Hello!When I run the codes in tutorial Spatial integration and clustering,it raises error AttributeError: 'ArrayView' object has no attribute 'todense' when I run STAligner_obj = ov.space.pySTAligner(adata_concat, verbose=True, knn_neigh = 100, n_epochs = 600, iter_comb = iter_comb,batch_key = 'batch_name',  key_added='STAligner', Batch_list = Batch_list,device = 'cpu').Perhaps it is due to the version of scipy.However, my scipy version is 1.11.4 which is <1.12 required by the requirement.txt.It really confuses me.Hopefully it can be solved.
<img width="1049" alt="屏幕截图 2024-11-09 193419" src="https://github.com/user-attachments/assets/5d5c8a6d-559d-4d97-908b-ff5a41913683">
<img width="599" alt="屏幕截图 2024-11-09 193603" src="https://github.com/user-attachments/assets/571099c9-fac9-40dc-b000-f77554b5d2cb">
platform:jupyter on vscode in Windows11

**Comment by DBinary** [comment]
Maybe your adata.X object is Array, not sparse matrix.
So you could convert the data structure of adata_concat.X to the sparse matrix format with the following code:
```
from scipy.sparse import csr_matrix
adata_concat.X = csr_matrix(adata_concat.X)
```

**Comment by GhostInTheShellwjc** [comment]
@DBinary Thank you for your help, but I'm sorry to inform you that the method you provided doesn't seem to have solved my problem effectively. I resolved the issue by modifying the __init__ function within the class pySTAligner in "D:\Miniconda3\envs\omicverse\Lib\site-packages\omicverse\space\_integrate.py" ,swapping the order of code execution.And it works well.

![image](https://github.com/user-attachments/assets/9f79da25-694c-408f-a31d-dd089e4b1cdb)
![image](https://github.com/user-attachments/assets/0d223d38-f6cf-4bd9-8ded-bd969207c650)

**Comment by HendricksJudy** [comment]
Sir, after testing the specific script.

Fix AttributeError in `pySTAligner` class by converting `adata.X` to sparse matrix format.

* **omicverse/space/_integrate.py**
  - Import `csr_matrix` from `scipy.sparse`.
  - Convert `adata_tmp.X` to sparse matrix format using `csr_matrix` before passing it to `STAligner`.
  - Update `train` method to handle 'ArrayView' objects by converting them to dense arrays using `toarray()`.

* **omicverse/externel/STAligner/STALIGNER.py**
  - Import `csr_matrix` from `scipy.sparse`.
  - Add check in `forward` method to convert `features` to sparse matrix format if not already.
  - Convert `features` to dense array using `toarray()` before passing to `conv1`.

You may apply this change until a better universal solution update in the next version.

**Comment by HendricksJudy** [comment]
Sir, does this method works in your device?  I have limited OS device (Mac&Linux) to test this solution.

**Comment by GhostInTheShellwjc** [comment]
I'm very sorry, but I have switched to using WSL to run omicverse now instead of the Windows platform, so I can't reproduce the issue.
