### ISSUE TITLE
ValueError: 'box_aspect' and 'fig_aspect' must be positive

### ISSUE THREAD

**Issue by GhostInTheShellwjc** [Starlitnightly/omicverse#215]
When I use module WGCNA,it raises error ValueError: 'box_aspect' and 'fig_aspect' must be positive.It may be a problem of WGCNA(#67 in PyWGCNA).Hopefully it can be solved or the WGCNA module can be updated to the latest version in next version of omicverse.
version:omicverse:1.6.8
platform:jupyter on vscode in Windows11

<img width="1205" alt="屏幕截图 2024-11-23 115329" src="https://github.com/user-attachments/assets/01599a58-294b-41b0-a618-a612246511ee">

<img width="1202" alt="屏幕截图 2024-11-23 115307" src="https://github.com/user-attachments/assets/6fff1cb5-b13a-4001-afbe-428a1823f66d">

<img width="992" alt="屏幕截图 2024-11-23 115242" src="https://github.com/user-attachments/assets/c9400f39-6cbd-4c67-9506-c48b02065cfe">

**Comment by Starlitnightly** [comment]
We don't support the funcyion `analysisWGCNA`, please read our tutorial and run step by step.

Tutorial for wgcna: https://omicverse.readthedocs.io/en/latest/Tutorials-bulk/t_wgcna/#pre-processing-workflow
