### ISSUE TITLE
Hoping for Updates to Pandas and NumPy Versions in Future Releases, Along with Other Suggestions

### ISSUE THREAD

**Issue by GhostInTheShellwjc** [Starlitnightly/omicverse#216]
Dear Starlitnightly：
Hello! The Omicverse package is the best bioinformatics Python package I've encountered, but I've recently encountered seemingly unsolvable version errors during use. For instance, PyVIA can only run on versions of pandas greater than 2.0, while PAGA and SCSA can only run on versions of pandas below 2.0 (#214, #211, #193). These conflicts seem irreconcilable, so I'm forced to install two different versions of pandas for Omicverse: one at 1.5.3 and another at 2.2.3. Sometimes I have to run it in another environment due to using the wrong one, which really frustrates me. NumPy is mainly used for Numba acceleration and as a foundational package, which is heavily relied on by many other packages. The errors caused by incorrect version correspondence between NumPy and Numba sometimes also bother me. I hope that in future versions, the pandas and NumPy versions can be updated, and more stringent version specifications can be added to the requirements. BTW, I also hope to see more content added to the TCGA module (such as enrichment analysis tailored for TCGA, WGCNA applicable to TCGA, as well as enrichment gene intersections, and even the ability to use regression to test correlations). Lastly, I hope that Omicverse continues to thrive and improve!
                         Yours,
                             sincerely

**Comment by Starlitnightly** [comment]
Currently only SCSA in OmicVerse is required to run on Pandas 1.5.3 and below, due to the formatted storage of the CellMarker database. In future releases of CellVote, we will synchronize the update of the SCSA database dependency. PAGA and pyVIA have no restriction on the version of pandas.
