### ISSUE TITLE
some problem in sc-enrichment analyses

### ISSUE THREAD

**Issue by Silencewu7** [Starlitnightly/omicverse#217]
`sub_adata_aucs=ov.single.pathway_aucell_enrichment(sub_adata,pathways_dict=pathway_dict,num_workers=8)
sub_adata_aucs.obs=sub_adata[sub_adata_aucs.obs.index].obs
sub_adata_aucs.obsm=sub_adata[sub_adata_aucs.obs.index].obsm
sub_adata_aucs.obsp=sub_adata[sub_adata_aucs.obs.index].obsp
`
InvalidIndexError: Reindexing only valid with uniquely valued Index objects

I copied the codes from your official tutorials and just replaced all the 'adata'  with 'sub_adata', because of the previous procedure of extracting of cell subgroup. Dont know how to fix it.

**Comment by Starlitnightly** [comment]
you need to run `adata.var_names_make_unique()` and `adata.obs_names_make_unique()` at first.
