### ISSUE TITLE
About function scanpy_lazy

### ISSUE THREAD

**Issue by GhostInTheShellwjc** [Starlitnightly/omicverse#218]
The omicverse package offers a plethora of clustering methods! However, many of these methods have not been integrated into the ov.single.scanpy_lazy function. Take mde as an example (BTW,ov.pp.mde only supports CUDA and seemingly lacks a non-CUDA option, although ov.utils.mde can run on non-CUDA graphics cards, such as my iris integrated graphics card. It is hoped that an option can be added to ov.pp.mde). Methods like GMM,cNMF,cosg,LDA
, which are provided by omicverse ,are not available in scanpy_lazy. It is hoped that more parameters can be added to this function or that a new function named omicverse_lazy can  be created to replace the functionality of scanpy_lazy, incorporating existing preprocessing methods into this function. Wish omicverse continues to improve and thrive!

**Comment by Starlitnightly** [comment]
Sorry, this function is not an officially released function, we might add a `lazy` function in the future, but not now.
