### ISSUE TITLE
standardized data after batch effects removal by Harmony

### ISSUE THREAD

**Issue by faker1c** [Starlitnightly/omicverse#22]
How to obtain standardized data after batch effects removal by Harmony for differential analysis between two groups of cells？

**Comment by Starlitnightly** [comment]
Hi, 

Unlike Bulk transcriptomes, scRNA-seq removal of batch effects does not change data values, but rather for better clustering

**Comment by faker1c** [comment]
Hi,I still have some questions when using it.
For data from different articles, is it possible to use the dds.deg_analysis function to calculate differential expression without removing batch effects? Can we simply use the standardized adata.X?
The sc.tl.rank_genes_groups function documentation does not mention how to use the use_rep parameter. When calculating marker genes, does adding use_rep='X_harmony' mean that adata.obsm["X_harmony"] is used for the calculation instead of adata.X?

**Comment by Starlitnightly** [comment]
> Hi,I still have some questions when using it. For data from different articles, is it possible to use the dds.deg_analysis function to calculate differential expression without removing batch effects? Can we simply use the standardized adata.X? The sc.tl.rank_genes_groups function documentation does not mention how to use the use_rep parameter. When calculating marker genes, does adding use_rep='X_harmony' mean that adata.obsm["X_harmony"] is used for the calculation instead of adata.X?

I don't think dds.deg_analysis can work better for single-cell data because single-cell data is too sparse, moreover, X_harmony can be used as a feature vector for cells, but its not representative of genes

**Comment by faker1c** [comment]
Thanks！
Does this mean that for single-cell sequencing data from different sources, after integration and processing with sc.pp.normalize_total and sc.pp.log1p, it is possible to directly perform differential expression, GO, and KEGG analysis, without the need for batch correction like in bulk RNA-seq?
