### ISSUE TITLE
Best Practices for Pre-processing RMA-normalized Data for WGCNA Analysis

### ISSUE THREAD

**Issue by LCGaoZzz** [Starlitnightly/omicverse#227]
### Description
I have been following the tutorial provided by omicverse for the PyWGCNA package, which discusses the pre-processing workflow for WGCNA analysis. The tutorial specifically mentions removing genes with too many missing values or those that are lowly-expressed across samples, suggesting a default TPM cutoff below 1 for gene removal. However, my data consists of expression levels normalized using the Robust Multi-array Average (RMA) method, which includes background correction and log2 transformation.

Given the nature of RMA normalization, I am unsure how to properly adjust the pre-processing steps for WGCNA analysis. The tutorial and the package seem tailored to TPM data, and I am experiencing unexpected results with my RMA-normalized data.

### Questions
1. **Adjusting Pre-processing for RMA Data**: What adjustments would you recommend for pre-processing RMA-normalized data before performing WGCNA? Specifically, are there any considerations or modifications needed in terms of handling genes with missing values or low expression?
   
2. **Log-transformed RMA Data**: Since RMA data is already log-transformed, should any further transformation be applied before conducting WGCNA? How does this affect the default settings in PyWGCNA, such as TPM cutoffs?

3. **Best Practices**: Could you provide any best practices or guidance on preparing RMA-normalized data for WGCNA, to ensure accurate module detection and gene network analysis?

### Additional Information
- **Data Description**: The data I am working with has been processed using the RMA algorithm, including background correction and log2 transformation.
- **Desired Outcome**: I aim to correctly preprocess my data for WGCNA to explore gene co-expression networks accurately.

I appreciate any insights or recommendations you could provide regarding the correct preprocessing steps for RMA-normalized data in the context of WGCNA analysis.

Thank you!

[Link to the omicverse PyWGCNA tutorial](https://www.omicverse.com/pywgcna/tutorial/preprocessing)

**Comment by Starlitnightly** [comment]
Thanks for using omicverse, the `PyWGCNA` encapsulated in OmicVerse is unrestricted with respect to the input, you need to grasp the robustness of the output for yourself.
