### ISSUE TITLE
Request for Additional Features

### ISSUE THREAD

**Issue by GhostInTheShellwjc** [Starlitnightly/omicverse#228]
The omicverse package is truly exceptional! It would be perfect if some new features were added!

1. Could a function be incorporated to download data from GEO or other databases（like Geoquery in R）, and extract data such as the expression matrix and pdata (if these are included in the downloaded data)?

2. If the downloaded data is traditional transcriptome data like RNA-seq, could corresponding functions be added for preliminary processing (e.g., converting values to TPM, FPKM, etc., based on species)? For scRNA-seq data, could a parameter be added to the ov.read() function to include metadata or grouping data (if present) as obs in adata (as some data's metadata and grouping data are not presented as obs and need to be added separately, but in R's Seurat objects, these data are included in meta.data, such as GSE174401).

3. SingleR is a cell annotation method in R. Could it be integrated into omicverse as one of its annotation methods?

4. I hope the single_cell_tutorial written by Starlitnightly (link:https://single-cell-tutorial.readthedocs.io/zh/latest/（https://single-cell-tutorial.readthedocs.io/zh/latest/）) (which is also a tutorial using omicverse) can be integrated into the existing tutorials. That tutorial includes some content not found in the current omicverse tutorials, such as cell composition analysis. BTW, some functions used in cell composition analysis need to be updated, referring to the pertpy official website tutorial. However, the tree in the tutorial crashes the Jupyter kernel when rendered. I hope this issue can be resolved when updating the tutorial. 
Thank you very much if these features can be added to omicverse!

**Comment by Starlitnightly** [comment]
Thanks for your advice.

1. Currently many single-cell data formats are not stored in a standardized format on GEO, so this feature is of little significance.

2. You can stored the information to `adata.uns['interested']`.

3. We are currently integrating the development of the `CellVote` algorithm, which is being developed by xuehai @HendricksJudy , with the aim of achieving automated annotation of single cells and maintaining a very high accuracy rate.

4. Some of the methods in the Best of Single Cells tutorial are not implemented in OmicVerse, perhaps you need a Chinese version of the tutorial, we may fulfill this need in a future release.

Best,
Zehua

**Comment by GhostInTheShellwjc** [comment]
Thank you very much for your reply to this!
