### ISSUE TITLE
_SCSA 流程中出现的bug解决

### ISSUE THREAD

**Issue by H1207953831** [Starlitnightly/omicverse#232]
**Describe the bug**
有3个bug，第一个bug是：
There are 3 bugs, the first bug is:
```python
# _SCSA.py line145
    def do_go_annotation(self,gof,fore,back,cname,gtype):
        """return go annotation with significance tag"""
        fil = gof[2].map(lambda value: len(set([value]) & fore) > 0)
        fgnames = gof[fil].groupby(by=4)[2].unique()
        bfil = gof[2].map(lambda value: len(set([value]) & back) > 0)
        bgnames = gof[bfil].groupby(by=4)[2].unique()
#KeyError：2
```

在pandas=2.x中,指定columns,应该使用字符串而不是直接使用数字！下面是修改后的。
In pandas=2.x, when specifying columns, strings should be used instead of numbers directly! Below is the modified version.
```python
    def do_go_annotation(self,gof,fore,back,cname,gtype):
        """return go annotation with significance tag"""
        fil = gof['2'].map(lambda value: len(set([value]) & fore) > 0)
        fgnames = gof[fil].groupby(by="4")["2"].unique()
        bfil = gof["2"].map(lambda value: len(set([value]) & back) > 0)
        bgnames = gof[bfil].groupby(by="4")["2"].unique()
```

第2个bug是所给的db文件中包含`ISO-8859-1`编码的非间断空格符等莫名其妙的字符。修复方式如下：
The second bug is that the given db file contains inexplicable characters such as `ISO-8859-1` encoded non-breaking spaces. Here’s how to fix it:
```python
# _SCSA.py line110
    def to_output(h_values,wb,outtag,cname,title):
        if outtag.lower() == "ms-excel":
            h_values.to_excel(wb,sheet_name = "Cluster " + cname + " " + title,index=False)
        else:
            def clean_non_printable_chars(value):
                """移除字符串中的非打印字符"""
                if isinstance(value, str):
                    return ''.join(c for c in value if c.isprintable())
                return value
            h_values = h_values.applymap(clean_non_printable_chars)
            h_values.to_csv(wb,sep="\t",quotechar = "\t",index=False,header=False,encoding='gbk')

```

第三个bug是生成的`rna_anno.txt`文件也是属于`ISO-8859-1`编码，导致pandas=2.x无法正常读取。修复方式如下：
The third bug is that the generated `rna_anno.txt` file also belongs to `ISO-8859-1` encoding, causing pandas=2.x to be unable to read normally. Here’s how to fix it:
```python
# 总共有4个地方，每个地方都是有
# There are 4 places in total, each place has
self.wb = open(self.output,"w")
self.wbgo = open(self.output + ".go","w")

#修改如下：
self.wb = open(self.output,"w", encoding='utf-8')
self.wbgo = open(self.output + ".go","w", encoding='utf-8')
```

由于没办法分享新生生成的db文件，所以在新的db文件请参考：
[https://github.com/Starlitnightly/omicverse/issues/176](https://github.com/Starlitnightly/omicverse/issues/176)

**Comment by HendricksJudy** [comment]
To better understand your request, could you translate the Chinese into English? This will benefit more users who check this issue.

**Comment by Starlitnightly** [comment]
Thanks to your contribution, we've released an updated SCSA database that can be loaded on pandas>2! And the omicverse version needs to be greater than 1.6.9 to load the database correctly! The database can be downloaded from [Google Drive](https://drive.google.com/file/d/1gg2m-edV2Jff8krWovsNb0jxv8A-DFol/view?usp=drive_link) and [百度云](https://pan.baidu.com/s/1o7w48z8_5QRlUAjz9auUQg?pwd=j6mp). 

Best,
Zehua
