### ISSUE TITLE
windows platform Process raise RuntimeError

### ISSUE THREAD

**Issue by H1207953831** [Starlitnightly/omicverse#236]
当我在搞dotplot的时候，发现了在windows平台的multiprocessing 似乎不支持，同时还报错了。
```run
  File "D:\坚果云\atom项目\70个项目实战\tmp\test.py", line 160, in <module>
    adata_aucs = ov.single.pathway_aucell_enrichment(adata_raw,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ML\Lib\site-packages\omicverse\single\_scgsea.py", line 174, in pathway_aucell_enrichment
    aucs_mtx = aucell(matrix, signatures=test_gmt, auc_threshold=auc_threshold, num_workers=num_workers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ML\Lib\site-packages\omicverse\single\_aucell.py", line 249, in aucell
    create_rankings(exp_mtx, seed),
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ML\Lib\site-packages\omicverse\single\_aucell.py", line 208, in aucell4r
    for p in processes:
        ^^^^^^^^^
  File "D:\Program Files\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "D:\Program Files\Python311\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
```
这似乎是特定平台导致的。在未来我可能提出通用的解决方案，等我研究两天

**Comment by Starlitnightly** [comment]
Thanks for debugging, you can try submitting a pr. the process is as follows:

Certainly! If you prefer to work directly on the main branch and use GitHub's web interface for creating a pull request, you can do so. However, it's generally a good practice to use separate branches for different changes. Here's how you can proceed with the local clone step included:

1. **Fork the Repository**:
   - Go to the repository you want to contribute to on GitHub and click the "Fork" button to create a copy under your GitHub account.

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/8c6607a2-6d3c-4e64-bb86-606c7f2f5402" />


2. **Clone the Forked Repository Locally**:
   - Clone your forked repository to your local machine:
     ```bash
     git clone <your-forked-repo-url>
     ```
   - Navigate into the cloned repository:
     ```bash
     cd <repository-name>
     ```


3. **Make Changes on the Main Branch**:
   - If you decide not to create a new branch, you can make changes directly on the main branch of your local clone. 

4. **Commit Your Changes**:
   - Stage your changes:
     ```bash
     git add <file-names>
     ```
   - Commit the changes:
     ```bash
     git commit -m "Description of the changes made"
     ```

5. **Push Changes to Your Fork**:
   - Push your changes to the main branch of your forked repository:
     ```bash
     git push origin main
     ```

6. **Create a Pull Request on GitHub**:
   - Go to the original repository on GitHub.
   - Click on the "Pull Requests" tab, then the "New Pull Request" button.
   - Choose the branch from your fork that contains your changes.
   - Fill in the necessary details and submit the pull request.

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/93ce56b6-2158-4af3-b8c6-f56c8213e086" />

And then you can found a new `pull request` in `Starlitnightly's OmicVerse`. Using pr allows you to appear as a contributor to the omicverse!
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/d742e979-6a95-44ec-b631-ffb4acbb5e9b" />

Best,
Zehua

**Comment by H1207953831** [comment]
我发现只要`num_worker=1`时，可以工作，所以根据平台的来强制更改`num_worker`数量
I found that it can work as long as `num_worker=1`, so I forcefully change the number of `num_worker` according to the platform.
```python
# _scgsea.py 
import os
num_workers = 1 if os.name == 'nt' else num_workers
```
