### ISSUE TITLE
A bug about ov.single.batch_correction()

### ISSUE THREAD

**Issue by WeiQin2001** [Starlitnightly/omicverse#239]
I install the latest version of omicverse, but there is a bug related to the "ov.single.batch_correction()",when I have run this ov.single.batch_correction() function and end up , my adata will get some error and the data within adata will be cleaned.

**Comment by WeiQin2001** [comment]
![image](https://github.com/user-attachments/assets/35eabad7-51ce-4b02-a834-12cad041c470)

**Comment by WeiQin2001** [comment]
![image](https://github.com/user-attachments/assets/eaf3aa3a-878b-4aa5-acb2-7147eba5988a)

**Comment by WeiQin2001** [comment]
![image](https://github.com/user-attachments/assets/f2487e06-7ebd-4dc7-8d44-cb05b382047f)
SCVI also get the similar condition, the adata will be removed.

**Comment by Starlitnightly** [comment]
In the version 1.6.9, we remove the return value. The vector space after batch-correction is now stored directly into the input `adata`, which reduces memory overhead. For scvi, we will return the `model` of scvi so that it can be used later on scANVI.

You can read the latest tutorial: https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_single_batch/

**Comment by WeiQin2001** [comment]
I get it!!! Thank you for your response!!!



| |
魏钦
|
|
***@***.***
|


---- Replied Message ----
| From | Zehua ***@***.***> |
| Date | 12/22/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Starlitnightly/omicverse] A bug about ov.single.batch_correction() (Issue #239) |

In the version 1.6.9, we remove the return value. The vector space after batch-correction is now stored directly into the input adata, which reduces memory overhead. For scvi, we will return the model of scvi so that it can be used later on scANVI.

You can read the latest tutorial: https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_single_batch/

**Comment by WeiQin2001** [comment]
尊敬的omicverse作者：
       您好！昨天在收到您的回复后，我看了您提到的最新教程，我发现新增了cellanova，这是一个新发布的批次整合算法，用于解决平衡在批次整合中平衡去除批次效应与保留生物学效应的问题，我阅读了原文献，作者似乎建议cellANOVA与其他现有整合算法如harmony结合进行单细胞批次整合，因为cellANOVA最大的特点是在保留生物学效应，而在当初批次矫正可能并不比其他现有算法好，我在您最后做得benchmarking test上也发现了这一点，请问怎么在omicverse中将cellanova与其他算法如harmony结合进行批次效应矫正呢？
      期待您的回复！








| |
魏钦
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/22/2024 16:57 |
| To | ***@***.***> |
| Subject | Re: [Starlitnightly/omicverse] A bug about ov.single.batch_correction() (Issue #239) |
I get it!!! Thank you for your response!!!



| |
魏钦
|
|
***@***.***
|


---- Replied Message ----
| From | Zehua ***@***.***> |
| Date | 12/22/2024 16:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Starlitnightly/omicverse] A bug about ov.single.batch_correction() (Issue #239) |

In the version 1.6.9, we remove the return value. The vector space after batch-correction is now stored directly into the input adata, which reduces memory overhead. For scvi, we will return the model of scvi so that it can be used later on scANVI.

You can read the latest tutorial: https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_single_batch/
