### ISSUE TITLE
presence of down regulated genes in the pathway analysis with AUCell

### ISSUE THREAD

**Issue by khanthanan** [Starlitnightly/omicverse#33]
hi, 
thank you for creating an awesome computational pipeline. 
i have a quick question regarding the usage of AUCell for pathway analysis. as far as i know, the enrichment terms consist of both up and down regulated genes. so I'm concerned about using AUCell for pathway analysis since it captures the signature based on gene ranking in each cell. so the presence of down regulated genes in the query list would decrease the AUCell score and would not provide an accurate picture. 

Just wanted to know whether it would be an issue or i am missing something, 
thank you again,
Best, 
Kalpana

**Comment by Starlitnightly** [comment]
I'm sorry I missed your issue, this is a valuable issue you mention, similar to other enrichment analysis methods, AUCell is still concerned with whether the gene is involved in the pathway, and does not involve up- or down-regulation relationships. Similar to finding the top 100 genes in a certain type of cell and seeing how many are within that pathway. So if the gene is down-regulated, then he won't be in the top 100 genes and it won't affect the AUCell score for that cell.

Zehua

**Comment by khanthanan** [comment]
Thank you very much for getting back to me. I totally agree with your statement. It's going in parallel with what SCENIC does for regulons.  However, in your tutorial, https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_aucell/, you plot the AUCell scores for enrichment term 'response to vitamin (GO:0033273)'. I'll give you an example, so that I could explain it properly. Let's say you have cells corresponding to a disease and control samples and you are calculating the AUCell scores for a disease related enrichment term. So this gene list consists of both up-and down- regulated genes corresponding to that disease. So when you calculate the AUCell scores for disease cells, the upregulated genes come into the calculation and provide their enrichment. Similarly, the down regulated genes would be enriched in the control cells. So both groups have non-zero AUCell scores so it might not show much of a difference. Similarly, in some diseases, there could be many downregulated genes, resulting in higher AUCell enrichment to the control group. Does that make sense?

thank you again for your response, 
Best, 
Kalpana

**Comment by Starlitnightly** [comment]
I'm sorry for replying to your message so late, the problem you mentioned is an inherent flaw of AUCell, which can't distinguish between up- and down-regulated genes in a gene set, perhaps there are other gene set enrichment methods that can compensate for this, if you find out about it please don't hesitate to let me know in time and I'll add it to OmicVerse.
