### ISSUE TITLE
implement other GPU based package to handel large scale cells (>1 million)

### ISSUE THREAD

**Issue by xflicsu** [Starlitnightly/omicverse#38]
Hi, omicverse integrated several useful methods related almost all the aspects of scRNA analysis.
With the large datasets producing, GPU show great power to speed up the analysis.
So, coulud you integrate other GPU based methods  to handel million cells?

The rapids_singlecell maybe one suitable for task more than one million cells.

**Comment by Starlitnightly** [comment]
Hi, 

The processed of large scale cells will add in `omicverse`'s next version.

Sincerely,

Zehua
