### ISSUE TITLE
Inquiry about Preprocessing with Specific Gene Exclusion Based on "Liver tumour immune microenvironment subtypes and neutrophil heterogeneity" Study

### ISSUE THREAD

**Issue by lisch7** [Starlitnightly/omicverse#39]
Hi,

I recently read the article "Liver tumour immune microenvironment subtypes and neutrophil heterogeneity" and was intrigued by the methodological approach, particularly the part about removing certain genes listed in the supplementary table.

![image](https://github.com/Starlitnightly/omicverse/assets/103273640/3610a759-9a92-4545-aec4-86c01f344927)

Is it possible to incorporate this gene list into the preprocess function like no_cc to exclude these genes from being considered in the identification of highly variable genes? Or maybe you could add a function to exclude specific gene list when find high variable genes?

Thank you for your time and assistance.

**Comment by Starlitnightly** [comment]
Thanks for your advice, we will add exclude specific gene list as parameter in `omicverse`'s next version.

Sincerely,

Zehua
