### ISSUE TITLE
Some errors when i pip this package

### ISSUE THREAD

**Issue by chulexuexibiedebushihewo** [Starlitnightly/omicverse#42]
Python3.8
when I use pip to install omicverse, there are always existing some errors. Do you know what caused this and how to resolve it?
![image](https://github.com/Starlitnightly/omicverse/assets/94608750/1450d795-737d-4bbe-8ae9-aa950a5af5d9)
![image](https://github.com/Starlitnightly/omicverse/assets/94608750/97b93de1-6cc4-4113-a88b-6f307f0be31c)

**Comment by Starlitnightly** [comment]
Hi,

OmicVerse is currently only compatible with Linux. You can install WSL (Windows Subsystem for Linux) to use Linux on Windows.

<img width="993" alt="image" src="https://github.com/Starlitnightly/omicverse/assets/46667721/3eec6fa2-9047-49f4-9dbc-05f2ebc73fd2">

**Comment by chulexuexibiedebushihewo** [comment]
OK, Thanks
