### ISSUE TITLE
scikit-learn module conflicts

### ISSUE THREAD

**Issue by lisch7** [Starlitnightly/omicverse#44]
Hi,

Recently, I followed the instructions to apply trajectory Inference (https://omicverse.readthedocs.io/en/latest/Tutorials-single/t_traj/). But I found out omicverse and scVelo require different versions of scikit-learn. OV required scikit-learn>=1.2 (https://github.com/Starlitnightly/omicverse/blob/master/pyproject.toml) but scVelo required scikit-learn>=0.21.2, <1.2.0 (https://github.com/theislab/scvelo/blob/main/pyproject.toml) . I wonder whether it will influence the analysis of the pipline.

Thanks for your kind help!

**Comment by Starlitnightly** [comment]
Hi,

In my environment, I have a version of scikit-learn installed that is greater than 1.2, and at the same time I don't have any problems with scVelo. I hope this helps for you.

Sincerely,
Zehua
