### ISSUE TITLE
A problem about the TCGA survival analysis

### ISSUE THREAD

**Issue by CocoGzh** [Starlitnightly/omicverse#46]
Dear authors,
Thank you for your contribution to the community.
I am having trouble with the TCGA Survival Analysis tutorial. Could you please provide me with the gdc_sample_sheet, gdc_download_files, and clinical_cart data? Alternatively, could you explain what the generated aml_tcga_raw.h5ad file contains?
Best wishes, 
gzh

**Comment by Starlitnightly** [comment]
Hi,

The data can be downloaded from [GDC](https://portal.gdc.cancer.gov/cart):

![f43e2417a01eb1075da46490599a3115](https://github.com/Starlitnightly/omicverse/assets/46667721/f144c023-c303-4102-82c2-1507cce41a97)
