### ISSUE TITLE
A question about the existence of randomness in OV computed metacells

### ISSUE THREAD

**Issue by Doctorluka** [Starlitnightly/omicverse#49]
Hi Dr.Zeng,

Thanks for the excellent OV tutorials and OV has become my favorite python package. However, I'm having some problems with randomness when using ov to infer metacell. Following the codes in tutorial [单细胞测序最好的课程（十一）](https://mp.weixin.qq.com/s/-CCOM0eZyhJa9aAglfYJbg),  I noticed that the umap graphs I calculated didn't match the ones in the tutorial. It should be emphasized that I did not change the code of the tutorial at all.

For example (The left graph is from the tutorial, the right is from my calculations) :
![image](https://github.com/Starlitnightly/omicverse/assets/101385826/6c05e435-d68f-40ba-8395-be9253a2a564)

or
![image](https://github.com/Starlitnightly/omicverse/assets/101385826/57562621-3c70-4785-8d8f-3a2779c6445b)

And then the auto-calculated fold-change is different:
> in tutorial : `Fold change threshold: 1.4815978396550413`  
in my results: `Fold change threshold: 2.487487769064068`

Even if I manually set fc = 1.48, the difference is still a bit big.
![image](https://github.com/Starlitnightly/omicverse/assets/101385826/2aa31dbc-a278-4373-8cf4-dc1a55f0afb5)

The surprise, however, was that there wasn't much difference when visualizing a particular gene.
![image](https://github.com/Starlitnightly/omicverse/assets/101385826/2591ea54-97b2-4092-b713-bf5b762c1cc5)

May I ask how this type of phenomenon can be explained and how the tutorial can be reproduced exactly?

As a former R user, I've only recently started using Python for single-cell analysis, so I don't really understand stochastic events for deep learning. **Is it possible to fix these random events in OV ?**

By the way, a question, **is it possible to add some parameters to allow the user to easily add statistics to barplot ?** Because I find that labeling p-values in the plot can be a bit confusing for users like me.

Thank you very much for reading! I hope I have articulated the problem clearly -.-

**Comment by Doctorluka** [comment]
Another question to add, given the heterogeneity between subgroups or samples, should the metacell be calculated independently by sample ? I don't know much about algorithms, can you explain why? Thanks!

**Comment by Starlitnightly** [comment]
> Hi Dr.Zeng,
> 
> Thanks for the excellent OV tutorials and OV has become my favorite python package. However, I'm having some problems with randomness when using ov to infer metacell. Following the codes in tutorial [单细胞测序最好的课程（十一）](https://mp.weixin.qq.com/s/-CCOM0eZyhJa9aAglfYJbg), I noticed that the umap graphs I calculated didn't match the ones in the tutorial. It should be emphasized that I did not change the code of the tutorial at all.
> 
> For example (The left graph is from the tutorial, the right is from my calculations) : ![image](https://private-user-images.githubusercontent.com/101385826/295783341-6c05e435-d68f-40ba-8395-be9253a2a564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTQxNTYsIm5iZiI6MTcwNDk1Mzg1NiwicGF0aCI6Ii8xMDEzODU4MjYvMjk1NzgzMzQxLTZjMDVlNDM1LWQ2OGYtNDBiYS04Mzk1LWJlOTI1M2EyYTU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNjE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTFmOTUxZDkyMWQ3NzA2YWIzMDdiNjgxMjRhYmI5NGY3MTkyMWExMjUwMTc4MjVlYmEwYmFiMDE0YTgzMzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wZnvug3CirXH9Zab7fjaPsitRt2cZxgKzgTSkj3QAsc)
> 
> or ![image](https://private-user-images.githubusercontent.com/101385826/295783468-57562621-3c70-4785-8d8f-3a2779c6445b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTQxNTYsIm5iZiI6MTcwNDk1Mzg1NiwicGF0aCI6Ii8xMDEzODU4MjYvMjk1NzgzNDY4LTU3NTYyNjIxLTNjNzAtNDc4NS04ZDhmLTNhMjc3OWM2NDQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNjE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzFiMTIxN2JlMDEwNDVmYmNkODViYzY5MzEzYjk1YzNiMmQxN2U4ZjNlZGVhZDVhODQyYWQ3N2U5MWQ4OTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H9ktinAMTHChaQggP28_O9NTc6Zmi4bg5uofEKzEz0c)
> 
> And then the auto-calculated fold-change is different:
> 
> > in tutorial : `Fold change threshold: 1.4815978396550413`
> > in my results: `Fold change threshold: 2.487487769064068`
> 
> Even if I manually set fc = 1.48, the difference is still a bit big. ![image](https://private-user-images.githubusercontent.com/101385826/295783580-2aa31dbc-a278-4373-8cf4-dc1a55f0afb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTQxNTYsIm5iZiI6MTcwNDk1Mzg1NiwicGF0aCI6Ii8xMDEzODU4MjYvMjk1NzgzNTgwLTJhYTMxZGJjLWEyNzgtNDM3My04Y2Y0LWRjMWE1NWYwYWZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNjE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDBhMzMwMmViY2EyMmFkNGZkZThiZDJiNDI0YWM5NGM3ZjMwZWRjYjgzMTM5MjFjNDUyM2VkYTk2NmM0NzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PJCwESWs6EQR47Rmaasbh3i45PdGOopiNSpWXYgj5EE)
> 
> The surprise, however, was that there wasn't much difference when visualizing a particular gene. ![image](https://private-user-images.githubusercontent.com/101385826/295783669-2591ea54-97b2-4092-b713-bf5b762c1cc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTQxNTYsIm5iZiI6MTcwNDk1Mzg1NiwicGF0aCI6Ii8xMDEzODU4MjYvMjk1NzgzNjY5LTI1OTFlYTU0LTk3YjItNDA5Mi1iNzEzLWJmNWI3NjJjMWNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNjE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWEzNjkxN2NmMzMyODk4ZDM2NGI5ODc2ZGZkOWQyZjZmMGY5ZmZiYzFlMDJkZDRlNTMwMTk3NmQ4ZDQwZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7XH1TS6dV7NoQAh0IQC9XBYvVKe1kHPopO4veDQOUOQ)
> 
> May I ask how this type of phenomenon can be explained and how the tutorial can be reproduced exactly?
> 
> As a former R user, I've only recently started using Python for single-cell analysis, so I don't really understand stochastic events for deep learning. **Is it possible to fix these random events in OV ?**
> 
> By the way, a question, **is it possible to add some parameters to allow the user to easily add statistics to barplot ?** Because I find that labeling p-values in the plot can be a bit confusing for users like me.
> 
> Thank you very much for reading! I hope I have articulated the problem clearly -.-

Thanks for your support of omicverse.

-1. The calculation of umap is subject to random seed interference, so just make sure the visualisation is consistent, there is no method to ensure that umap is exactly the same every time, see the explanation of seed in machine learning.
-2. The aggregation of metacells is also a deep learning process, due to the inconsistency of the random seed seed, so the metacells trained by each aggregation will be different, so the foldchange will also be different, just need to make sure that the most significant differences in the genes are consistent.
-3. The addition of p-values is really a matter of concern, I will add the relevant plotting function in subsequent versions, or you can use the following function to manually plot the p-values if you need to.

```python
#plot line
plt.plot((0,1),(2,2),c='#000000')
#plot pvalue/*
plt.text((1+0)/2,2.5,
         '$p=0.01$',horizontalalignment='center',fontsize=10)
```
This code will draw a line between the horizontal coordinates 0, 1, at a height of 2, with the p-value labelled above.

sincerely
Zehua

**Comment by Starlitnightly** [comment]
> Another question to add, given the heterogeneity between subgroups or samples, should the metacell be calculated independently by sample ? I don't know much about algorithms, can you explain why? Thanks!

Yes, you can calculate the metacell independently by sample. In our tutorial, I calculate the metacells on the embedded X_scVI after removing the batch effect or the embedded X_pca without removing the batch effect for convenience as well as to remove the batch effect. Only I name the cell type labels and samples in tandem via celltype-sample.

Zehua

**Comment by Doctorluka** [comment]
Thanks for your patient answer. Tandem celltype and sample is a good idea, and I am trying to apply it in my own research. I'm looking forward to omicverse's continued updates.

**Comment by Doctorluka** [comment]
> > Another question to add, given the heterogeneity between subgroups or samples, should the metacell be calculated independently by sample ? I don't know much about algorithms, can you explain why? Thanks!
> 
> Yes, you can calculate the metacell independently by sample. In our tutorial, I calculate the metacells on the embedded X_scVI after removing the batch effect or the embedded X_pca without removing the batch effect for convenience as well as to remove the batch effect. Only I name the cell type labels and samples in tandem via celltype-sample.
> 
> Zehua

Hi Dr.Zeng,

I'll add a small question: even though my umap plot and metacell have some randomness (I've repeated the run to confirm), why is the number of metacells 250 in each case? Is this also a coincidence? If I get a larger amount of data, say 100000 cells, will it also be only 250?

Here is the latest results :
```Python
ad=meta_obj.predicted(method='soft',celltype_label='celltype-label',
                     summarize_layer='lognorm')
# 100%|██████████| 250/250 [01:06<00:00,  3.74it/s]

ad
# AnnData object with n_obs × n_vars = 250 × 2000
#    obs: 'Pseudo-sizes', 'celltype', 'celltype_purity'
```
