### ISSUE TITLE
Could not show the pictures after run the code "ov.utils.embedding" in WSL2

### ISSUE THREAD

**Issue by DestinyXuanQAQ** [Starlitnightly/omicverse#51]
**Describe the bug**
Previously, running this code in WSL1 allowed images to appear, but after a recent I update it to WSL2 and this code does not allow images to appear anymore.
The version is 1.5.6

**To Reproduce**

ov.pp.scale(adata)
ov.pp.pca(adata,layer='scaled',n_pcs=50)

adata.obsm["X_mde_pca"] = ov.utils.mde(adata.obsm["scaled|original|X_pca"])
ov.utils.embedding(adata,
                basis='X_mde_pca',frameon='small',
                color=['batch','cell_type'],show=False)

it just exports 

[<AxesSubplot: title={'center': 'batch'}, xlabel='X_mde_pca1', ylabel='X_mde_pca2'>,
 <AxesSubplot: title={'center': 'cell_type'}, xlabel='X_mde_pca1', ylabel='X_mde_pca2'>]

**Expected behavior**
It will export a picture to show me the picture about the results of PCA analysis.

**Screenshots**
![1705302834220](https://github.com/Starlitnightly/omicverse/assets/93072350/da5f06b1-c820-4c8d-b475-9dcf5b74d8c9)

**Desktop (please complete the following information):**
 - windows10 WSL2
 - Version:  Ubuntu 20.04
 -  Vscode

**Additional context**
I tried to install Xlaunch to deal with this, and the matplotlib code outputs the image properly, but this code still doesn't work.

**Comment by Starlitnightly** [comment]
You need to add `%matplotlib inline` before your code.

Zehua
