### ISSUE TITLE
DEG  plot_volcano  KeyError: 'explode'

### ISSUE THREAD

**Issue by wanglifangelena** [Starlitnightly/omicverse#53]
**Describe the bug**
Hello, thanks for your work of omicverse. 
I recently applied it (version 1.5.7) on DEGs analysis, found that there are confusing problem. 

1. It runs quite soon when  the dataset was CD4 T cells of 'kang.h5ad' (test_adata), while quite slowly when I just use "kang.h5ad" (adata), even though the cell number of data is twice of test_adata... adata.shape=25,461*2000, test_adata.shape=11,760*2000, why the speed for dds.deg_analysis process differ from each other much. And of my personal dataset, it is near 100,000 cells, a lot more difficult to process it.

2. a  KeyError: 'explode' when I tried to plot a volcano plot by using DEG results. 

![image](https://github.com/Starlitnightly/omicverse/assets/133332947/c51f85bd-3e2e-411f-9f06-270b8027128a)
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/77b2245b-e629-4d4c-8347-e5b8baaa9d7a)

Thanks very much if the problems can be resolve!

**Comment by Starlitnightly** [comment]
Hi,

- For the first question, I think it's because you chose the `DEseq2` mode, which needs to fit the NB model, so the calculations are slower, the tutorial compares the different modes, and there is no problem using `ttest`.
- For the second question, the problem is caused by too high version of adjustText, you can lower the version to `0.8`, we will fix this issue in the next version of `omicverse` and optimise the volcano plotting.

Zehua

**Comment by wanglifangelena** [comment]
Hi, Zehua:
 
Thanks for your promptly reply, the second problem was resolved when I change the version of adjusttext as 0.7.3. While I'd like to continue discuss more with the first problem.

When I run test_adata (CD4T cells of kang.h5ad),  the records are like:
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/a05e9cb5-5d8a-4ef8-877e-e40c77047b75)
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/0f227d4c-0b05-419f-81e0-73cf0d689ebb)
When I run adata(kang.h5ad),the records are like:
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/ae847097-1bf9-4dbd-b41b-9c33fe7bc058)
I can't get further progress within 2 hr....
when I used my personal adata, same records with kang.h5ad, they are like:
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/440afd66-7b0d-4ade-8cd8-5ebdaf69b823)

It has been running for 2days, and I am doubting whether my adata has any problem?? the cost time could be so long even need to fit NB model?? 
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/8aeee230-2571-4f3c-919c-aad51648e945)

And besides, when I run pp.qc process on my server, it shows illegal instruction: core dumped.
![image](https://github.com/Starlitnightly/omicverse/assets/133332947/f52d72b5-e08a-4b42-b3e2-56c7b2f0a24e)
Any idea about this problem?

Thank you very much for your contribution to omicverse and assistance to me!

Best regards,
Lifang

**Comment by wanglifangelena** [comment]
For the first problem, I saw the differences of records are: diapersions trend curve, logres_prior and sigma_prior..... so I am thinking whether the data structures are of some mistakes?? Just guessing..

**Comment by Starlitnightly** [comment]
This looks like a memory overflow and it is not recommended that you use DEseq2 to analyse on all cells.
