### ISSUE TITLE
A problem about batch correction in single-cell-tutorial's code

### ISSUE THREAD

**Issue by DestinyXuanQAQ** [Starlitnightly/omicverse#54]
**Describe the bug**
It is a KeyError when I use this code.

**To Reproduce**
simba_object.gen_graph()
simba_object.train(num_workers=6)
adata2=simba_object.batch_correction() # This code can not run and say that KeyError
adata.obsm['X_simba']=adata2.obsm['X_simba'].copy()

**out put**
[out put.txt](https://github.com/Starlitnightly/omicverse/files/14000498/out.put.txt)

**Expected behavior**
Batch correction

**Screenshots**
![ca54f16f45f22b8c544cef675722256](https://github.com/Starlitnightly/omicverse/assets/93072350/be5fb3d3-d169-495f-a82d-92df89c72797)
![1f69e98a97041d125c334357b3f55a4](https://github.com/Starlitnightly/omicverse/assets/93072350/9044e9ff-1084-4834-9b95-4b4cdcc9a5c0)

**Desktop (please complete the following information):**
omicverse 1.5.7
WSL2 ubuntu20.04
windows10

**Additional context**
The tutorial is 
https://single-cell-tutorial.readthedocs.io/zh/latest/preprocess/2-5/

**Comment by Starlitnightly** [comment]
@mugpeng There seems to be something wrong with your pull request #27

**Comment by mugpeng** [comment]
Could you provide your input obj or with the similar structure?

**Comment by DestinyXuanQAQ** [comment]
> Could you provide your input obj or with the similar structure?

I am following this tutorial to run the code, all the data and code is there 
https://single-cell-tutorial.readthedocs.io/zh/latest/preprocess/2-5/

The wrong is occurring in the part  "基于细胞与特征共嵌入图".

**Comment by mugpeng** [comment]
Please check #56 @Starlitnightly
