### ISSUE TITLE
Error pathway enrichment figure by using ov.bulk.geneset_plot

### ISSUE THREAD

**Issue by wanglifangelena** [Starlitnightly/omicverse#55]
Hi, Zehua:

I got another error when I plot pathway enrichment figure by using ov.bulk.geneset_plot:

![image](https://github.com/Starlitnightly/omicverse/assets/133332947/307f2bb4-b1ee-446b-8313-b2e00be42a7c)

Please help to see what is going wrong  there.
Thank you!

Best,
Lifang

**Comment by Starlitnightly** [comment]
You can try updating or downgrading your numpy version or matplotlib version to fix the problem.
