### ISSUE TITLE
Error in enrich_res=gsea_obj.enrichment()

### ISSUE THREAD

**Issue by erwusht** [Starlitnightly/omicverse#59]
**Describe the bug**
Error when run `enrich_res=gsea_obj.enrichment()`

**To Reproduce**
1. `pathway_dict=ov.utils.geneset_prepare('genesets/GO_Biological_Process_2021.txt',organism='Human')`
2. `rnk=dds.ranking2gsea()`
3. `gsea_obj=ov.bulk.pyGSEA(rnk,pathway_dict)`
4. `enrich_res=gsea_obj.enrichment()`

**Expected behavior**
```
KeyError: 'fdr'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[15], line 1
----> 1 enrich_res=gsea_obj.enrichment()

File omicverse/bulk/_Enrichment.py:437, in pyGSEA.enrichment(self, format, pval, seed)
    433 pre_res=geneset_enrichment_GSEA(self.gene_rnk,self.pathways_dict,
    434                                    self.processes,self.permutation_num,
    435                                    self.outdir,format,seed)
    436 self.pre_res=pre_res
--> 437 enrich_res=pre_res.res2d[pre_res.res2d['fdr']<pval]
    438 enrich_res['logp']=-np.log(enrich_res['fdr']+0.0001)
    439 enrich_res['logc']=enrich_res['nes']

File pandas/core/frame.py:3807, in DataFrame.__getitem__(self, key)
   3805 if self.columns.nlevels > 1:
   3806     return self._getitem_multilevel(key)
-> 3807 indexer = self.columns.get_loc(key)
   3808 if is_integer(indexer):
   3809     indexer = [indexer]

File pandas/core/indexes/base.py:3804, in Index.get_loc(self, key, method, tolerance)
   3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:
-> 3804     raise KeyError(key) from err
   3805 except TypeError:
   3806     # If we have a listlike key, _check_indexing_error will raise
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 'fdr'
```

**Additional context**
dds.plot_volcano(title='DEG Analysis',figsize=(4,4), plot_genes_num=2,plot_genes_fontsize=12,) works correctly
my gseapy version = 1.1.1 and I can not install gseapy =0.10.8 because 
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

**Comment by Starlitnightly** [comment]
This function does not necessarily return results if not enriched for differentially expressed genes

**Comment by erwusht** [comment]
Hi, when I use `gseapy =0.10.8`, it works, it failed in `gseapy =1.1.1` environment, and `gseapy =1.1.1` is the default version for installation.
