### ISSUE TITLE
bug in survial_init

### ISSUE THREAD

**Issue by aopisco** [Starlitnightly/omicverse#62]
Thanks for these tcga utils! I'm getting an error with `survial_init` that points to [these lines](https://github.com/Starlitnightly/omicverse/blob/238770a997f53cb0cc47a45c695c671025ef6468/omicverse/bulk/_tcga.py#L98). The result of `.loc` is a single value so `.iloc[0]` doesn't exist.

**Comment by Starlitnightly** [comment]
I'm sorry, can you provide details of the error report?
