### ISSUE TITLE
Where is the function  ov.pl.cellproportion?

### ISSUE THREAD

**Issue by christophechu** [Starlitnightly/omicverse#64]
I'm using 1.5.7

https://omicverse.readthedocs.io/en/latest/Tutorials-plotting/t_visualize_single/

according to the page, there is no function named pl.

is it using 1.5.8??
where is the version 1.5.8

**Comment by Starlitnightly** [comment]
Now that version 1.5.8 has been officially released, it's important to note that if you want to get early access to the new version's features, consider getting it from the github

```shell
pip install git+https://github.com/Starlitnightly/omicverse.git
```

Zehua

**Comment by Mei918** [comment]
AttributeError                            Traceback (most recent call last)
Cell In[181], line 2
      1 fig,ax=plt.subplots(figsize = (1,4))
----> 2 ov.pl.cellproportion(adata=rna_adata, celltype_clusters='scsa_celltype_cellmarker',
      3                     groupby='group',legend=True,ax=ax)

AttributeError: module 'omicverse' has no attribute 'pl'

I got this error when used ov.pl.cellproportion function and I have installed latest version of omicverse.
