### ISSUE TITLE
LibMambaUnsatisfiableError: Encountered problems while solving

### ISSUE THREAD

**Issue by pickingastar** [Starlitnightly/omicverse#70]
Hello, I followed your instructions to install the OmicVerse package, but I received the following result:
conda install omicverse -c conda-forge
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
 - nvidia
 - pyg
 - pytorch
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides scikit-misc >=0.1 needed by omicverse-1.4.11-pyhd8ed1ab_0

Could not solve for environment specs
The following package could not be installed
└─ omicverse is not installable because it requires
   └─ scikit-misc >=0.1 , which does not exist (perhaps a missing channel).

I used the "pip freeze" command to check the version of scikit-misc, and it showed version 0.3.1. However, I encountered the aforementioned error, and I'm unsure how to resolve it. Could you please help me? Thank you.

**Comment by Starlitnightly** [comment]
Hi, 

Thanks for your support of omicverse. 

<img width="737" alt="image" src="https://github.com/Starlitnightly/omicverse/assets/46667721/86975540-ee63-47f1-a852-fe63d0a2c31f">

**Comment by pickingastar** [comment]
> Hi,
> 
> Thanks for your support of omicverse.
> 
> <img alt="image" width="737" src="https://private-user-images.githubusercontent.com/46667721/321637489-86975540-ee63-47f1-a852-fe63d0a2c31f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTEwMjUsIm5iZiI6MTcxMjg5MDcyNSwicGF0aCI6Ii80NjY2NzcyMS8zMjE2Mzc0ODktODY5NzU1NDAtZWU2My00N2YxLWE4NTItZmU2M2QwYTJjMzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyNTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkN2MzNDNiMDE3YjA2MDdkZTgwMDNiYzAzZDUyMGVhY2Q5NmVkMjM5Mjk1NjM3MGY1NDZkMWFhYjAxNTBhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8TyoDkpGK-1d5PoAEXJNpuT-YZQ7EpVMBBv-PQMrP0c">

it works,thank you so much.I  overlooked important steps and information before.
