### ISSUE TITLE
Sample (dataset) question in the tutorial

### ISSUE THREAD

**Issue by asd519627326** [Starlitnightly/omicverse#72]
Hello, I am studying bioinformatics, I don't know a lot of knowledge, I would like to ask what kind of (tissue) genes are used in the sample (dataset) used in the tutorial "different Expression Analysis with DEseq2"?

**Comment by Starlitnightly** [comment]
Hi,

The kind of sample in tutorials is mouse skin.

**Comment by asd519627326** [comment]
> Hi,
> 
> The kind of sample in tutorials is mouse skin.教程中的示例类型是鼠标皮肤。

Thank you very much for your reply
