### ISSUE TITLE
Installation Win

### ISSUE THREAD

**Issue by RubyLiu206** [Starlitnightly/omicverse#75]
Hi,

Thank you for developing this wonderful tool! I was trying to install under my local environment, and I encountered with the following error: 

>         File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "C:\Users\Anaconda3\envs\omicverse\envs\omicverse\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\Anaconda3\envs\omicverse\envs\omicverse\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Anaconda3\envs\omicverse\envs\omicverse\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Anaconda3\envs\omicverse\envs\omicverse\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I used pip to install, everything else went smoothly except the pip install -U omicverse

**Comment by Starlitnightly** [comment]
Hi,

Thanks for your support, the same issue could be found in #70

**Comment by RubyLiu206** [comment]
> Hi,
> 
> Thanks for your support, the same issue could be found in #70

Thanks for forwarding. I actually successfully installed under HPC. However, I have a follow-up question, do you think VAE over-integrating, or over-performed that make all samples with the same cell type composition. Refer as the below image: 
![image](https://github.com/Starlitnightly/omicverse/assets/42716532/e3ad5ba3-530b-4a84-a972-7ebc2bc5348b)


I used our in-house bulk rna data, and GEO immune cell data (n_obs × n_vars = 93900 × 28638), using 2000 genes for cell type deconvolution.

**Comment by RubyLiu206** [comment]
I really appreciate you quick response!! I see you point. I choose 2k was because of CIBERSORT used signature matrix from 500 to 2000 number of genes. I will try with 28638 genes with 500 as top marker for sure.
