### ISSUE TITLE
 H should have the same dtype as X. Got H.dtype = float32.

### ISSUE THREAD

**Issue by christophechu** [Starlitnightly/omicverse#85]
In cnmf it has been solved, But in omicverse  its still here.

**Comment by christophechu** [comment]
cnmf_obj.consensus(k=selected_K, 
                   density_threshold=density_threshold, 
                   show_clustering=True, 
                   close_clustergram_fig=False)

**Comment by christophechu** [comment]
add norm_tpm.X = norm_tpm.X.astype(np.float32) and norm_counts.X = norm_counts.X.astype(np.float32) can solve this problem

**Comment by Starlitnightly** [comment]
Hi, I can't reproduce the problem you're posing, can you give a detailed input/output case, and what is reported as an error?

Zehua

**Comment by Starlitnightly** [comment]
We have fixed this error in omicverse 1.6.6
