### ISSUE TITLE
When using bulk2single, should the bulk data use counts, tpm, deseq_normalize, or other types of data?

### ISSUE THREAD

**Issue by Hennery02** [Starlitnightly/omicverse#94]
Dear Omicverse Team,

First of all, I would like to extend my sincere congratulations on the amazing work you have done with Omicverse. It has been incredibly helpful for my research, and I appreciate all the effort you have put into developing this tool.

I have a question regarding the use of the bulk2single function. When using bulk2single, should the bulk data be in the form of counts, TPM, DESeq normalized values, or some other type of data?

Thank you very much for your assistance and for your continuous contributions to the scientific community. I look forward to your guidance.

Best regards

**Comment by Starlitnightly** [comment]
Hi, 

You need to make sure that Bulk and scRNA-seq use the same form of normalisation, e.g. in our [tutorials](https://starlitnightly.github.io/omicverse/Tutorials-bulk2single/t_bulk2single/#loading-data), both use counts.

Zehua

**Comment by Hennery02** [comment]
Thank you very much for your prompt response to my previous question.

I noticed that when running **CellFractionPrediction = model.predicted_fraction()**, the following message appears: "Normalizing raw single cell data with scanpy.pp.normalize_total". I am unsure whether the bulk data requires the same normalization treatment.

Thank you once again for your valuable assistance.

**Comment by Starlitnightly** [comment]
> Thank you very much for your prompt response to my previous question.
> 
> I noticed that when running **CellFractionPrediction = model.predicted_fraction()**, the following message appears: "Normalizing raw single cell data with scanpy.pp.normalize_total". I am unsure whether the bulk data requires the same normalization treatment.
> 
> Thank you once again for your valuable assistance.

Hi,

I double-checked the input to bulk2single and it does ask for the raw unprocessed `COUNT`, which is the requirement for the cell fraction prediction.

Zehua
