### ISSUE TITLE
Request for TCGA analysis

### ISSUE THREAD

**Issue by Jonyyqn** [Starlitnightly/omicverse#95]
Hi, very impressed and useful tool ! I have a request for tcga analysis. If I obtain a cohort (such as TCGA-BRCA) gene expression matrix and clinical information through other channels, is there any quick way to construct a tcga object similar to the one in the chapter "TCGA database preprocessing" (aml_tcga in the example)?

**Comment by Starlitnightly** [comment]
Hi,

I can provide an example of tcga data and you can use your own data to make it according to the example.
But it may be early next month before I can finish this.

Zehua

**Comment by Jonyyqn** [comment]
> Hi,
> 
> I can provide an example of tcga data and you can use your own data to make it according to the example. But it may be early next month before I can finish this.
> 
> Zehua

Wow, Thank you very much !

**Comment by Starlitnightly** [comment]
TCGA OV: https://figshare.com/ndownloader/files/47461946
